/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "xbffontcreate.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_BUTTON_0  (GUI_ID_USER + 0x01)
#define ID_BUTTON_1  (GUI_ID_USER + 0x04)


// USER START (Optionally insert additional defines)
#define ID_TEXT_0  (GUI_ID_USER + 0x08)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 67, 186, 250, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 404, 186, 250, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 245, 99, 254, 50, 0, 0x0, 0 },
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN      hItem;
  int NCode;
  int Id;

  switch (pMsg->MsgId) {
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {
            case ID_BUTTON_0: // Notifications sent by 'Button'
                switch(NCode) {
                    case WM_NOTIFICATION_CLICKED:
                    // USER START (Optionally insert code for reacting on notification message)
                    // USER END
                    break;
                    case WM_NOTIFICATION_RELEASED:
                    // USER START (Optionally insert code for reacting on notification message)
                    // USER END
                    break;
                  // USER START (Optionally insert additional code for further notification handling)
                  // USER END
                }
            break;
            case ID_BUTTON_1: // Notifications sent by 'Button'
                switch(NCode) {
                      case WM_NOTIFICATION_CLICKED:
                        // USER START (Optionally insert code for reacting on notification message)
                        // USER END
                        break;
                      case WM_NOTIFICATION_RELEASED:
                        // USER START (Optionally insert code for reacting on notification message)
                        // USER END
                        break;
                      // USER START (Optionally insert additional code for further notification handling)
                      // USER END
                }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
            }
    break;
      // USER START (Optionally insert additional message handling)
   case WM_INIT_DIALOG:

        hItem = WM_GetDialogItem(pMsg->hWin,ID_TEXT_0);
        //Create_XBF36("system/XBF宋体36.xbf");//创建xbf36号路径
        TEXT_SetFont(hItem,&XBF36_Font);
        TEXT_SetText(hItem,"请选择支付方式");
        //f_close(&XBF36FontFile);
        //GUI_Delay(3);

        hItem = pMsg->hWin;
        //Create_XBF24("system/XBF宋体24.xbf");//创建xbf36号路径
        FRAMEWIN_SetTextAlign(hItem,GUI_TA_HCENTER | GUI_TA_VCENTER);
        FRAMEWIN_SetTitleHeight(hItem,40);
        FRAMEWIN_SetFont(hItem,&XBF24_Font);
        FRAMEWIN_SetTextColor(hItem,GUI_RED);
        FRAMEWIN_SetText(hItem,"欢迎使用北京动力源科技股份有限公司交流充电桩");

        hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_0);
        BUTTON_SetFont(hItem,&XBF24_Font);
        BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_BLUE);
        BUTTON_SetText(hItem,"手机支付请扫描二维码");

        hItem = WM_GetDialogItem(pMsg->hWin,ID_BUTTON_1);
        BUTTON_SetFont(hItem,&XBF24_Font);
        BUTTON_SetTextColor(hItem,BUTTON_CI_DISABLED,GUI_BLUE);
        BUTTON_SetText(hItem,"刷卡支付请刷卡");
        //f_close(&XBF24FontFile);
        //GUI_Delay(3);

        //GUI_DispCharAt();
        break;
      // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin1(void);
WM_HWIN CreateFramewin1(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
void PutOut_Home1()
{
    CreateFramewin();
    while(1)
    {
        dispbmp("system/dpc.bmp",0,5,5,1,1);
        //bmpdisplay("system/dpc.bmp");
        GUI_Delay(1);
    }
}
// USER END

/*************************** End of file ****************************/
