/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                               _hWinManagerSysInfo                     *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "touchtimer.h"
// USER END

#include "DIALOG.h"

#include "includes.h"

#include "order.h"
#include "interface.h"
#include "utils.h"
#include "cJSON.h"
#include "evse_config.h"
#include "cfg_parse.h"
#include "stringName.h"
#include "errorcode.h"
#include <string.h>
#include "yaffsfs.h"

#define BYTES_LEN 1024

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_1  (GUI_ID_USER + 0x01)
#define ID_BUTTON_2  (GUI_ID_USER + 0x02)
#define ID_LISTVIEW_0   (GUI_ID_USER + 0x04)

#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x05)
#define ID_TEXT_1     (GUI_ID_USER + 0x03)
#define ID_BUTTON_3  (GUI_ID_USER + 0x06)
#define ID_BUTTON_4  (GUI_ID_USER + 0x07)


#define ID_TimerTime    1
#define ID_TimerFlush   2
#define ID_TimerSignal  3

#define ALARM_COLUMNS   4
#define CHARGE_COLUMNS  20
#define DB_DEBUG    0

#define sysInfoName "       系统信息"
#define sysInfoEVSEName "系统名称:7kW交流充电桩"
#define sysInfoProtoVer "协议版本:"
#define sysInfoVersion "软件版本:"

#define GUI_MANAGERSYSINFO_XLENTH 400

static WM_HTIMER _timerRTC, _timerData, _timerSignal;
uint16_t column_num, row_num;
WM_HWIN _hWinManagerSysInfo;
WM_HWIN _hWinFrame;
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "window", ID_WINDOW_0, 0, 40, 800, 440, 0, 0x0, 0 },
    { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 20, 40, GUI_MANAGERSYSINFO_XLENTH, 180, 0, 0x0, 0 },//560,276
//    { BUTTON_CreateIndirect, "清空数据", ID_BUTTON_3, 650, 100, 80, 50, 0, 0x0, 0 },
//    { BUTTON_CreateIndirect, "恢复默认", ID_BUTTON_4, 650, 200, 80, 50, 0, 0x0, 0 },
};

static const GUI_WIDGET_CREATE_INFO _aDialogCreateFrame[] =
{
    { FRAMEWIN_CreateIndirect, "!!!!", ID_FRAMEWIN_0, 250, 50, 300, 200, 0, 0x64, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 0, 50, 300, 50, TEXT_CF_HCENTER, 0x0, 0 },
    { BUTTON_CreateIndirect, "确定-重启", ID_BUTTON_3, 50, 110, 80, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "取消", ID_BUTTON_4, 200, 110, 80, 50, 0, 0x0, 0 },
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/** @brief 状态内容编辑分析
 *
 * @param
 * @param
 * @return
 *
 */
static void Status_Content_Analy(WM_MESSAGE *pMsg)
{
    CON_t *pCon;
    uint8_t tmp[10];
    uint8_t buf[50];
    WM_HWIN hItem;

    hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
    /**< 协议版本 */
    memset(buf, '\0', sizeof(buf));
    strcpy(buf, sysInfoProtoVer);
    memset(tmp, '\0', sizeof(tmp));
    sprintf(tmp, "%d", pechProto->info.ucProtoVer);
    strcat(buf, tmp);
    LISTVIEW_SetItemText(hItem, 0, 1, buf);
    LISTVIEW_AddRow(hItem, NULL);//增加一行
    /**< 软件版本 */
    memset(buf, '\0', sizeof(buf));
    strcpy(buf, sysInfoVersion);
    strcat(buf, xSysconf.strVersion);
    LISTVIEW_SetItemText(hItem, 0, 2, buf);
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog_frame_record(WM_MESSAGE *pMsg)
{
    WM_HWIN      hItem;
    int          NCode;
    int          Id;
    char buff[10];
    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        FRAMEWIN_SetFont(pMsg->hWin, &SIF24_Font);
        hItem = WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin), ID_TEXT_1);
        TEXT_SetFont(hItem, &SIF16_Font);
        TEXT_SetText(hItem, "将删除所有记录文件!");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetFont(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin), ID_BUTTON_3), &SIF16_Font);
        BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3), "确定-重启");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetFont(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin), ID_BUTTON_4), &SIF16_Font);
        BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4), "取消");
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_BUTTON_3:
            switch (NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                yaffs_unlink(pathOrder);
                yaffs_unlink(pathOrderTmp);
                yaffs_unlink(pathEVSELog);
                NVIC_SystemReset();
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_4:
            switch (NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                GUI_EndDialog(pMsg->hWin, 0);
                break;
            default:
                break;
            }
            break;
        }
    }
}

static void _cbDialog_frame_default(WM_MESSAGE *pMsg)
{
    WM_HWIN      hItem;
    int          NCode;
    int          Id;
    char buff[10];
    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        FRAMEWIN_SetFont(pMsg->hWin,&SIF24_Font);
        hItem = WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin), ID_TEXT_1);
        TEXT_SetFont(hItem, &SIF16_Font);
        TEXT_SetText(hItem, "将清空所有配置和记录文件!");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetFont(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin), ID_BUTTON_3), &SIF16_Font);
        BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3), "确定-重启");
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetFont(WM_GetDialogItem(WM_GetClientWindow(pMsg->hWin), ID_BUTTON_4), &SIF16_Font);
        BUTTON_SetText(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4), "取消");
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_BUTTON_3:
            switch (NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                yaffs_unlink(pathOrder);
                yaffs_unlink(pathOrderTmp);
                yaffs_unlink(pathEVSELog);
                yaffs_unlink(pathEVSECfg);
                yaffs_unlink(pathSysCfg);
                yaffs_unlink(pathFTPCfg);
                yaffs_unlink(pathProtoCfg);
                NVIC_SystemReset();
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_4:
            switch (NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                GUI_EndDialog(pMsg->hWin, 0);
                break;
            default:
                break;
            }
            break;
        }
    }
}

static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    volatile WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;
    uint16_t     i, _strNum[3];
    volatile HEADER_Handle hHeader;
    uint8_t    buf[50];
    uint8_t    tmp[10];
    //	static char  Value = 0;
    SCROLLBAR_Handle hScroll;
    SCROLLBAR_Handle wScroll;
    CON_t	*pcont;

//    static int _x,_y;
//    WM_SCROLL_STATE ScrollState;

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        break;
    case WM_INIT_DIALOG:
        if (managerLevel == 0)
        {
            BUTTON_CreateEx(450, 80, 80, 50, pMsg->hWin, WM_CF_SHOW, 0, ID_BUTTON_1);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
            BUTTON_SetFont(hItem, &SIF16_Font);
            BUTTON_SetText(hItem, "清空数据");
            BUTTON_CreateEx(450, 180, 80, 50, pMsg->hWin, WM_CF_SHOW, 0, ID_BUTTON_2);
            hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
            BUTTON_SetFont(hItem, &SIF16_Font);
            BUTTON_SetText(hItem, "恢复默认");
        }
        //
        // 初始列表控件
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
        /* 设置列表控件中header控件的所显示文本的字体 */
        hHeader = LISTVIEW_GetHeader(hItem);
        HEADER_SetFont(hHeader, &SIF36_Font);

        /* 设置列表控件选项中所显示文本的字体 */
        LISTVIEW_SetFont(hItem, &SIF24_Font);
        /* 设置列表控件表格可见 */
        LISTVIEW_SetGridVis(hItem, 1);

        column_num = LISTVIEW_GetNumColumns(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
        for (i = 0; i < column_num; i++)
        {
            LISTVIEW_DeleteColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0);
        }

        /*增加一列*/
        LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), GUI_MANAGERSYSINFO_XLENTH, sysInfoName, GUI_TA_VCENTER | GUI_TA_LEFT);
//        LISTVIEW_SetTextAlign(hItem, 1, GUI_TA_CENTER | GUI_TA_LEFT);

        LISTVIEW_AddRow(hItem, NULL);//增加一行
        /**< 7kW交流充电桩 */
        xSysconf.GetSysCfg((void *)&xSysconf, NULL);
        LISTVIEW_SetItemText(hItem, 0, 0, sysInfoEVSEName);
        LISTVIEW_AddRow(hItem, NULL);//增加一行
        /**< 协议版本 */
        memset(buf, '\0', sizeof(buf));
        strcpy(buf, sysInfoProtoVer);
        memset(tmp, '\0', sizeof(tmp));
        sprintf(tmp, "%d", pechProto->info.ucProtoVer);
        strcat(buf, tmp);
        LISTVIEW_SetItemText(hItem, 0, 1, buf);
        LISTVIEW_AddRow(hItem, NULL);//增加一行
        /**< 软件版本 */
        memset(buf, '\0', sizeof(buf));
        strcpy(buf, sysInfoVersion);
        strcat(buf, xSysconf.strVersion);
        LISTVIEW_SetItemText(hItem, 0, 2, buf);

        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_BUTTON_1:
            switch (NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                GUI_CreateDialogBox(_aDialogCreateFrame, GUI_COUNTOF(_aDialogCreateFrame), _cbDialog_frame_record, WM_GetClientWindow(pMsg->hWin), 0, 0);
                break;
            default:
                break;
            }
            break;
        case ID_BUTTON_2:
            switch (NCode)
            {
            case WM_NOTIFICATION_RELEASED:
                GUI_CreateDialogBox(_aDialogCreateFrame, GUI_COUNTOF(_aDialogCreateFrame), _cbDialog_frame_default, WM_GetClientWindow(pMsg->hWin), 0, 0);
                break;
            default:
                break;
            }
            break;
        }
    case WM_TIMER:
//        if(pMsg->Data.v == _timerRTC)
//        {
//            /**< 显示时间和日期 */
//            Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);
//           // TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), strCSQ);
//            /**< 重启定时器 */
//            WM_RestartTimer(pMsg->Data.v, 20);
//        }
//        if(pMsg->Data.v == _timerSignal)
//        {
//
//            WM_RestartTimer(pMsg->Data.v, 2000);
//        }
        if (pMsg->Data.v == _timerData)
        {
            Status_Content_Analy(pMsg);
            WM_RestartTimer(pMsg->Data.v, 3000);
        }
        break;
    case MSG_CREATERRWIN:
        /**< 故障界面不存在则创建,存在则刷新告警 */
        err_window(pMsg->hWin);
        break;
    case MSG_DELERRWIN:
        /**< 故障界面存在则删除故障界面 */
        if (bittest(winCreateFlag, 0))
        {
            bitclr(winCreateFlag, 0);
            GUI_EndDialog(err_hItem, 0);
            err_hItem = 0;
        }
        break;
    case MSG_DELETEMANAGERWIN:
        GUI_EndDialog(_hWinManagerSysInfo, 0);
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

/** @brief
 *  输出管理员界面里的信息状态量部分
 * @param
 * @param
 * @return
 *       CreateManagerSysInfo
*/
WM_HWIN CreateManagerSysInfo(WM_HWIN srcHwin)
{
    _hWinManagerSysInfo = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_GetClientWindow(srcHwin), 0, 0);
//    _timerRTC = WM_CreateTimer(WM_GetClientWindow(_hWinManagerSysInfo), ID_TimerTime, 20, 0);
    _timerData = WM_CreateTimer(WM_GetClientWindow(_hWinManagerSysInfo), ID_TimerFlush, 1000, 0);
//    _timerSignal = WM_CreateTimer(WM_GetClientWindow(_hWinManagerInfoAnalog), ID_TimerSignal,5000,0);
    return _hWinManagerSysInfo;
}
/*************************** End of file ****************************/










