/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*
*   数据变化刷新;
*   需要刷新更新发送刷新数据消息
*   multi更新数据
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "touchtimer.h"
#include "SCROLLBAR.h"
// USER END

#include "DIALOG.h"
/*******************************************************************
*
*       defines
*
********************************************************************
*/
/*编辑窗口14行1列，状态项14个*/
#define _SYSEDIT_MAX_X 5
#define _SYSEDIT_MAX_Y 16
#define _SYSSTATUE_LINE 20
#define _SYSSTATUE_CAL 5
//后续将编辑和文本的滚轮方式用链表进行封装
#define _FONT_WIDTH 7
#define _WORD_WIDTH 12
static uint8_t _aahSysSet[_SYSEDIT_MAX_Y];
static EDIT_Handle   _aahEdit[_SYSEDIT_MAX_Y][_SYSEDIT_MAX_X];
static TEXT_Handle   _aahText[_SYSSTATUE_LINE][_SYSSTATUE_CAL];
static int _x,_y;
static uint8_t _checkbox;
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0     (GUI_ID_USER + 0x00)
#define ID_IMAGE_0     (GUI_ID_USER + 0x1C)
// USER START (Optionally insert additional defines)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)

#define ID_BUTTON_0  (GUI_ID_USER + 0x00)//信息
#define ID_BUTTON_1  (GUI_ID_USER + 0x01)//历史
#define ID_BUTTON_2  (GUI_ID_USER + 0x02)//系统
#define ID_BUTTON_3  (GUI_ID_USER + 0x03)//退出
#define ID_BUTTON_4  (GUI_ID_USER + 0x04)//模拟
#define ID_BUTTON_5  (GUI_ID_USER + 0x05)//状态
#define ID_TEXT_5  (GUI_ID_USER + 0x06)//
#define ID_EDIT_0  (GUI_ID_USER + 0x07)//
#define ID_TEXT_6  (GUI_ID_USER + 0x08)//
#define ID_TEXT_7  (GUI_ID_USER + 0x09)//
#define ID_TEXT_8  (GUI_ID_USER + 0x0A)//
#define ID_TEXT_9  (GUI_ID_USER + 0x0F)//
#define ID_TEXT_10  (GUI_ID_USER + 0x10)//
#define ID_TEXT_11  (GUI_ID_USER + 0x11)//
#define ID_EDIT_1  (GUI_ID_USER + 0x12)//
#define ID_EDIT_2  (GUI_ID_USER + 0x13)//
#define ID_EDIT_3  (GUI_ID_USER + 0x14)//
#define ID_EDIT_4  (GUI_ID_USER + 0x15)//
#define ID_EDIT_5  (GUI_ID_USER + 0x16)//
#define ID_EDIT_6  (GUI_ID_USER + 0x17)//
#define ID_MULTIEDIT_0 (GUI_ID_USER + 0x18)
#define ID_CHECKBOX_0 (GUI_ID_USER + 0x19)
#define ID_CHECKBOX_1 (GUI_ID_USER + 0x1A)
#define ID_TimerTime    1
#define ID_TimerFlush   2
#define ID_TimerSignal  3

#define sysEVSESN "交流桩SN"
#define sysEVSEID "交流桩ID"
#define sysServerIP "服务器IP"
#define sysServerPort "服务器端口"
#define sysUserName "用户名"
#define sysUserPwd "用户密码"
#define sysDispSleepTime "屏保时间"
#define sysUSEGPRSModem "GPRS类型"
// USER END
static WM_HWIN hWindow;
static WM_HWIN _hWinManagerSysSet;
static WM_HTIMER _timerRTC,_timerData,_timerSignal;

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
// USER END
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Framewin", ID_WINDOW_0, 0, 20, 800, 300, 0, 0x64, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_0, GUI_MANAGER_XLEFT + _FONT_WIDTH*(strlen(sysUSEGPRSModem)), GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*7, 90, 32, 0, 0x0, 0 },
	{ CHECKBOX_CreateIndirect, "Checkbox", ID_CHECKBOX_1, GUI_MANAGER_XLEFT + _FONT_WIDTH*(strlen(sysUSEGPRSModem)) + 90, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*7, 90, 32, 0, 0x0, 0 },
};
/*******************************************************************
*
*       _cbWindow

  The callback moves the edit-fiels when a notification message
  was send.
*/
static void _cbWindow(WM_MESSAGE *pMsg) {
    WM_SCROLL_STATE ScrollState;
    WM_HWIN      hItem;
    int x, y;
    volatile int id = 0;
    volatile int v = 0;
    uint8_t _tmpBuff[50];
    CON_t *pCon;
    pCon = CONGetHandle(0);

    switch (pMsg->MsgId)
    {
        case WM_NOTIFY_PARENT:
            /**< 添加两个滑轮的事件 */
            switch(WM_GetId(pMsg->hWinSrc))
            {
                case GUI_ID_HSCROLL://水平
                    if(pMsg->Data.v == WM_NOTIFICATION_VALUE_CHANGED)
                    {
                        /* 得到滚动条的状态，得到的数值好像是负值 才能使得 _x - ScrollState.v是正值 */
                        WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
                        if (_x != ScrollState.v)
                        {
                            for (y = 0; y < _SYSEDIT_MAX_Y; y++)
                            {
                                for (x = 0; x < _SYSEDIT_MAX_X; x++)
                                {
                                    WM_MoveWindow(_aahEdit[y][x], _x - ScrollState.v, 0);
                                    WM_MoveWindow(_aahText[y][x], _x - ScrollState.v, 0);
                                }
                            }
                            _x = ScrollState.v;
                        }
                    }
                break;
                case GUI_ID_VSCROLL:
                    if(pMsg->Data.v == WM_NOTIFICATION_VALUE_CHANGED)
                    {
                        WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
                        if (_y != ScrollState.v)
                        {
                            for (y = 0; y < _SYSEDIT_MAX_Y; y++)
                            {
                                for (x = 0; x < _SYSEDIT_MAX_X; x++)
                                {
                                    WM_MoveWindow(_aahEdit[y][x],0, _y - ScrollState.v);
                                    WM_MoveWindow(_aahText[y][x],0, _y - ScrollState.v);
                                }
                            }
                            _y = ScrollState.v;
                        }
                    }
                break;
                case 20:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,20,hWindow,_hWinManagerSysSet,sysEVSESN,"eg,1122334455667788");
                        //Keypad_GetValue(SYSSET_VALUE,"交流桩序列号");
                        EDIT_SetText(_aahEdit[0][0],pEVSE->info.strSN);
                    }
                break;
                case 21:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,21,hWindow,_hWinManagerSysSet,sysEVSEID,"eg,1122334455667788");
                        memset(_tmpBuff,'\0',sizeof(_tmpBuff));
                        sprintf(_tmpBuff,"%d",pEVSE->info.strID);
                        EDIT_SetText(_aahEdit[1][0],_tmpBuff);
                    }
                break;
                case 22:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,22,hWindow,_hWinManagerSysSet,sysServerIP,"eg,192.168.1.101");
                        memset(_tmpBuff,'\0',sizeof(_tmpBuff));
                        sprintf(_tmpBuff,"%d",pechProto->info.strServerIP);
                        EDIT_SetText(_aahEdit[2][0],_tmpBuff);
                    }
                break;
                case 23:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,23,hWindow,_hWinManagerSysSet,sysServerPort,"eg,8080");
                        memset(_tmpBuff,'\0',sizeof(_tmpBuff));
                        sprintf(_tmpBuff,"%.1f",pechProto->info.usServerPort);
                        EDIT_SetText(_aahEdit[3][0],_tmpBuff);
                    }
                break;
                case 24:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,24,hWindow,_hWinManagerSysSet,sysUserName,"eg,dpc");
                        EDIT_SetText(_aahEdit[4][0],pechProto->info.strUserName);
                    }
                break;
                case 25:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,25,hWindow,_hWinManagerSysSet,sysUserPwd,"eg,8888");
                        EDIT_SetText(_aahEdit[5][0],"******");
                    }
                break;
                case 26:
                    if(pMsg->Data.v == WM_NOTIFICATION_CLICKED)
                    {
                        WM_HideWindow(hWindow);
                        WM_HideWindow(_hWinManagerSysSet);

                        Keypad_GetValueTest(SYSSET_VALUE,26,hWindow,_hWinManagerSysSet,sysDispSleepTime,"eg,5");
                        memset(_tmpBuff,'\0',sizeof(_tmpBuff));
                        sprintf(_tmpBuff,"%d",xSysconf.ulDispSleepTime_s);
                        EDIT_SetText(_aahEdit[4][0],_tmpBuff);
                    }
                break;
            }
            break;
        case WM_PAINT:
            /**< 绘制滑轮围绕区颜色 */
            GUI_SetBkColor(GUI_WHITE);
            GUI_Clear();
            break;
        default:
            WM_DefaultProc(pMsg);
    }
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;
    int x, y,Index;
    SCROLLBAR_Handle hScroll;
    SCROLLBAR_Handle wScroll;
    char _tmpBuff[50];
    CON_t *pCon;

    pCon = CONGetHandle(0);
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        //LCD_SetCursor(0,200);
        WM_SetFocus(pMsg->hWin);
        /// TODO (zshare#1#): 下面的if不起作用.\
        但是if里嵌套的if起作用,目前先用此来规避不起作用的if
        if(_hWinManagerSysSet == cur_win)
        {
            /**< 数据处理 */
            //Data_Process(pMsg);
            /**< 信号数据处理 */
            Signal_Show();
            /**< 灯光控制 */
            Led_Show();
            /**< 如果界面发生了切换 */
            if(_hWinManagerSysSet == cur_win)
            {
                /**< 故障分析 */
                /// TODO (zshare#1#): 滑轮页均不对故障处理.故障界面被滑轮页覆盖
                //Err_Analy(pMsg->hWin);
                /**< 特殊触控点分析 */
                CaliDone_Analy(pMsg->hWin);
            }
        }
        break;
    case WM_INIT_DIALOG:
        _x = 0;
        _y = 0;
        // 创建窗口250
        hWindow = WM_GetDialogItem(pMsg->hWin, ID_WINDOW_0);//WM_CreateWindow(230, 70, 520, 350, WM_CF_SHOW, &_cbWindow, 0);
        //创建水平滑轮
        hScroll = SCROLLBAR_CreateAttached(hWindow, 0);//水平滑轮
        //设置滑轮条目数量
        SCROLLBAR_SetNumItems(hScroll, _SYSEDIT_MAX_X);
        //设置页尺寸
        //SCROLLBAR_SetPageSize(hScroll, 220);
        SCROLLBAR_SetWidth(hScroll,20);
        //创建垂直滑轮
        wScroll = SCROLLBAR_CreateAttached(hWindow, SCROLLBAR_CF_VERTICAL);//垂直滑轮
        //设置滑轮条目数量
        SCROLLBAR_SetNumItems(wScroll, 25*10);
        //设置页尺寸
        //SCROLLBAR_SetPageSize(wScroll, 220);
        SCROLLBAR_SetWidth(wScroll,20);

        //创建文本区 -- 24号字体 4-96 5-120 6-144 7-168 8-192
        /**< 13文本固定id */
        //创建编辑区
        /**< 20-50编辑区ID */
        xSysconf.GetSysCfg((void *)&xSysconf, NULL);
        _aahText[0][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT, _FONT_WIDTH*(strlen(sysEVSESN)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysEVSESN);
        _aahEdit[0][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysEVSESN)), GUI_MANAGER_YLEFT, _WORD_WIDTH*(strlen("1122334455667788")), 25,hWindow,WM_CF_SHOW,0,20,strlen("1122334455667788"));
        EDIT_SetText(_aahEdit[0][0],pEVSE->info.strSN);

        _aahText[1][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF, _FONT_WIDTH*(strlen(sysEVSEID)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysEVSEID);
        _aahEdit[1][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysEVSEID)), 50, _WORD_WIDTH*(strlen("1122334455667788")) , GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,21,strlen("1122334455667788"));
        memset(_tmpBuff,'\0',strlen(_tmpBuff));
        sprintf(_tmpBuff,"%d",pEVSE->info.strID);
        EDIT_SetText(_aahEdit[1][0],_tmpBuff);

        _aahText[2][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*2, _FONT_WIDTH*(strlen(sysServerIP)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysServerIP);
        _aahEdit[2][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysServerIP)),260, _WORD_WIDTH*(strlen("255.255.255.255")), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,22,strlen("255.255.255.255"));
        memset(_tmpBuff,'\0',strlen(_tmpBuff));
        sprintf(_tmpBuff,"%d",pechProto->info.strServerIP);
        EDIT_SetText(_aahEdit[2][0],_tmpBuff);

        _aahText[3][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*3, _FONT_WIDTH*(strlen(sysServerPort)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysServerPort);
        _aahEdit[3][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysServerPort)), GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*3, _WORD_WIDTH*strlen("8080"), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,23,strlen("8080"));
        memset(_tmpBuff,'\0',strlen(_tmpBuff));
        sprintf(_tmpBuff,"%d",pechProto->info.usServerPort);
        EDIT_SetText(_aahEdit[3][0],_tmpBuff);

        _aahText[4][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*4, _FONT_WIDTH*(strlen(sysUserName)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysUserName);
        _aahEdit[4][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysUserName)),GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*4, _WORD_WIDTH*strlen("woshinidaye"), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,24,strlen("woshinidaye"));
        EDIT_SetText(_aahEdit[4][0],pechProto->info.strUserName);

        _aahText[5][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*5, _FONT_WIDTH*(strlen(sysUserPwd)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysUserPwd);
        _aahEdit[5][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysUserPwd)),GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*5, _WORD_WIDTH*strlen("******"), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,25,strlen("******"));
        EDIT_SetText(_aahEdit[5][0],"******");

        _aahText[6][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*6, _FONT_WIDTH*(strlen(sysDispSleepTime)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysDispSleepTime);
        _aahEdit[6][0] = EDIT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysDispSleepTime)), GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*6, _WORD_WIDTH*(strlen("100")), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,26,strlen("100"));
        _aahText[6][1] = TEXT_CreateEx(GUI_MANAGER_XLEFT+_FONT_WIDTH*(strlen(sysDispSleepTime))+_WORD_WIDTH*(strlen("100")), GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*6, _FONT_WIDTH*(strlen("分")), 25,hWindow,WM_CF_SHOW,0,13,"分");
        memset(_tmpBuff,'\0',strlen(_tmpBuff));
        sprintf(_tmpBuff,"%d",xSysconf.ulDispSleepTime_s);
        EDIT_SetText(_aahEdit[6][0],_tmpBuff);

        _aahText[7][0] = TEXT_CreateEx(GUI_MANAGER_XLEFT, GUI_MANAGER_YLEFT + GUI_MANAGER_YOFF*7, _FONT_WIDTH*(strlen(sysUSEGPRSModem)), GUI_MANAGER_YOFF,hWindow,WM_CF_SHOW,0,13,sysUSEGPRSModem);
        //初始化复选框
        _checkbox = 0;
        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
        CHECKBOX_SetText(hItem, "2G");
        CHECKBOX_SetFont(hItem, GUI_FONT_24B_ASCII);
        if(xSysconf.xModule.use_gprs == 0)
        {
            CHECKBOX_SetState(hItem,1);
            bitset(_checkbox,0);
        }
        else
        {
            CHECKBOX_SetState(hItem,0);
        }

        hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
        CHECKBOX_SetText(hItem, "4G");
        CHECKBOX_SetFont(hItem, GUI_FONT_24B_ASCII);
        CHECKBOX_SetState(hItem,0);

        for(x = 0;x < _SYSSTATUE_LINE;x++)
        {
            for(y = 0;y < _SYSSTATUE_CAL;y++)
            {
                TEXT_SetFont(_aahText[x][y], &SIF16_Font);
                TEXT_SetTextColor(_aahText[x][y], GUI_BLACK);
            }
        }

        for (y = 0; y < _SYSEDIT_MAX_Y; y++)
        {
            for (x = 0; x < _SYSEDIT_MAX_X; x++)
            {
                EDIT_SetTextAlign(_aahEdit[y][x], GUI_TA_HCENTER | GUI_TA_VCENTER);
                EDIT_SetFont(_aahEdit[y][x], &SIF16_Font);
            }
        }

        WM_SetStayOnTop(hWindow,1);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;

        switch(Id) {
        case ID_CHECKBOX_0:
            switch(NCode)
            {
                case WM_NOTIFICATION_CLICKED:
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_0);
                    Index = CHECKBOX_GetState(hItem);
                    if((Index == 1)&&(!bittest(_checkbox,0)))
                    {
                        bitset(_checkbox,0);
                        bitclr(_checkbox,1);
                        Index = 0;
                        xSysconf.SetSysCfg(jnSysUSE_GPRSModem,(void *)&Index,ParamTypeU8);
                    }
                    break;
                case WM_NOTIFICATION_RELEASED:
                    break;
                case WM_NOTIFICATION_VALUE_CHANGED:
                    break;
            }
            break;

        case ID_CHECKBOX_1:
            switch(NCode)
            {
                case WM_NOTIFICATION_CLICKED:
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_CHECKBOX_1);
                    Index = CHECKBOX_GetState(hItem);
                    if((Index == 1)&&(!bittest(_checkbox,1)))
                    {
                        bitset(_checkbox,1);
                        bitclr(_checkbox,0);
                        Index = 1;
                        xSysconf.SetSysCfg(jnSysUSE_GPRSModem,(void *)&Index,ParamTypeU8);
                    }
                    break;

                case WM_NOTIFICATION_RELEASED:
                    break;

                case WM_NOTIFICATION_VALUE_CHANGED:
                    break;

            }
            break;
        case ID_BUTTON_0: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
                /**< 跳转到信息查询 */
                WM_SetStayOnTop(hWindow,0);
                GUI_EndDialog(hWindow,0);
                _deleteWin(_hWinManagerSysSet);
                //CreateManagerInfoAnalog();
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_1: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
                /**< 跳转到历史记录查询 */
                WM_SetStayOnTop(hWindow,0);
                GUI_EndDialog(hWindow,0);
                _deleteWin(_hWinManagerSysSet);
//                CreateManagerAlarmLog();
            break;
          case WM_NOTIFICATION_RELEASED:

            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_2: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_3: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            /**< 跳转至home */
            WM_SetStayOnTop(hWindow,0);
            GUI_EndDialog(hWindow,0);
            _deleteWin(_hWinManagerSysSet);
            CreateHomePage();
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        }
        break;
        // USER START (Optionally insert additional message handling)
    case WM_TIMER:
        if(pMsg->Data.v == _timerRTC)
        {
            /**< 显示时间和日期 */
            Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), strCSQ);
            /**< 重启定时器 */
            WM_RestartTimer(pMsg->Data.v, 20);
        }
        if(pMsg->Data.v == _timerSignal)
        {
            WM_RestartTimer(pMsg->Data.v, 2000);
        }
        if(pMsg->Data.v == _timerData)
        {
            //Data_Flush(pMsg);
            //Status_Content_Analy();
            WM_RestartTimer(pMsg->Data.v,3000);
        }
        break;
    case MSG_CREATERRWIN:
        /**< 故障界面不存在则创建,存在则刷新告警 */
        err_window(pMsg->hWin);
        break;
    case MSG_DELERRWIN:
        /**< 故障界面存在则删除故障界面 */
        if(bittest(winCreateFlag,0))
        {
            bitclr(winCreateFlag,0);
            GUI_EndDialog(err_hItem,0);
            err_hItem = 0;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/** @brief
 *  输出管理员界面里的系统配置
 * @param
 * @param
 * @return
 *
 *
 *       CreateManagerSysSet
*/
WM_HWIN CreateManagerSysSet(WM_HWIN srcHwin)
{
    _hWinManagerSysSet = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_GetClientWindow(srcHwin), 0, 0);
    cur_win = _hWinManagerSysSet;
    _timerRTC = WM_CreateTimer(WM_GetClientWindow(_hWinManagerSysSet), ID_TimerTime, 20, 0);
    _timerData = WM_CreateTimer(WM_GetClientWindow(_hWinManagerSysSet), ID_TimerFlush,1000,0);
    _timerSignal = WM_CreateTimer(WM_GetClientWindow(_hWinManagerSysSet), ID_TimerSignal,5000,0);
}
/*************************** End of file ****************************/




