/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "touchtimer.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0  (GUI_ID_USER + 0x00)
#define ID_SCROLLBAR_0  (GUI_ID_USER + 0x01)
#define ID_SCROLLBAR_1  (GUI_ID_USER + 0x02)
#define ID_LISTWHEEL_0  (GUI_ID_USER + 0x03)
#define ID_LISTWHEEL_1  (GUI_ID_USER + 0x04)
#define ID_BUTTON_0  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_1  (GUI_ID_USER + 0x10)
#define ID_BUTTON_2  (GUI_ID_USER + 0x12)
#define ID_BUTTON_3  (GUI_ID_USER + 0x13)
#define ID_BUTTON_4  (GUI_ID_USER + 0x09)
#define ID_BUTTON_5  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_6  (GUI_ID_USER + 0x0B)
#define ID_BUTTON_7  (GUI_ID_USER + 0x0C)
#define ID_TEXT_0  (GUI_ID_USER + 0x0E)
#define ID_LISTWHEEL_2  (GUI_ID_USER + 0x05)
#define ID_LISTWHEEL_3  (GUI_ID_USER + 0x06)
#define ID_TEXT_1  (GUI_ID_USER + 0x11)
#define ID_LISTWHEEL_4  (GUI_ID_USER + 0x07)
#define ID_LISTWHEEL_5  (GUI_ID_USER + 0x08)
#define ID_MULTIEDIT_0  (GUI_ID_USER + 0x14)

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static const char *_apYear[]=
{
    "2004", "2005", "2006", "2007", "2008", "2009", "2010",
    "2011", "2012", "2013", "2014", "2015", "2016", "2017",
    "2018", "2019", "2020", "2021", "2022", "2023", "2024",
    "2025", "2026", "2027", "2028", "2029", "2030", "2031",
};
static const char *_apMonth[]=
{
    "01","02","03","04","05","06",
    "07","08","09","10","11","12",
};
static const char *_apDay[]=
{
    "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12",
    "13", "14", "15", "16", "17", "18",
    "19", "20", "21", "22", "23", "24",
    "25", "26", "27", "28", "29", "30", "31",
};
static DateStruct sel_start_date = {"2017","01","01"};
static DateStruct sel_end_date = {"2020","01","01"};
static uint8_t list_start_index[3];
static uint8_t list_end_index[3];
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "alarm", ID_FRAMEWIN_0, 0, -1, 800, 480, 0, 0x0, 0 },
//  { SCROLLBAR_CreateIndirect, "Scrollbar", ID_SCROLLBAR_0, 260, 338, 412, 15, 0, 0x0, 0 },
//  { SCROLLBAR_CreateIndirect, "Scrollbar", ID_SCROLLBAR_1, 657, 152, 15, 184, 8, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_0, 300, 95, 43, 50, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_1, 350, 95, 20, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 70, 120, 150, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 70, 184, 150, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_2, 70, 247, 150, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_3, 70, 312, 150, 50, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_4, 285, 40, 140, 40, 0, 0x0, 0 },//告警记录
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_5, 491, 40, 140, 40, 0, 0x0, 0 },//充电记录
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_6, 225, 367, 300, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_7, 552, 106, 56, 25, 0, 0x0, 0 },//查询
  { TEXT_CreateIndirect, "Date", ID_TEXT_0, 253, 110, 50, 31, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_2, 375, 95, 20, 50, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_3, 420, 95, 43, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "TO", ID_TEXT_1, 400, 110, 20, 20, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_4, 470, 95, 20, 50, 0, 0x0, 0 },
  { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_5, 495, 95, 20, 50, 0, 0x0, 0 },
  { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 260, 152, 468, 206, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  char    i;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Listwheel'
    //
    // USER START (Optionally insert additional code for further widget initialization)
    //初始化listwheel
    for(i = 0;i < 6;i++)
    {
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0+i);
        //设置字体
        LISTWHEEL_SetFont(hItem,&GUI_FontComic18B_ASCII);
        LISTWHEEL_SetTextAlign(hItem,GUI_TA_VCENTER | GUI_TA_VERTICAL);
        //设置吸附位置
        LISTWHEEL_SetSnapPosition(hItem,15);
        //设置绘制数据项所使用的行高
//        LISTWHEEL_SetLineHeight(hItem,30);
        //设置选中的条目的文本颜色
        LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_RED);
    }
    //设置起始年listwheel
    hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
    //绘制指示行
//    LISTWHEEL_SetOwnerDraw(hItem,ListWheel0_OwnerDraw);
    //添加数据
    for(i = 0;i < GUI_COUNTOF(_apYear);i++)
    {
        LISTWHEEL_AddString(hItem,*(_apYear+i));
    }

    //设置起始月listwheel
    hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
    //添加数据
    for(i = 0;i < GUI_COUNTOF(_apMonth);i++)
    {
        LISTWHEEL_AddString(hItem,*(_apMonth+i));
    }

    //设置起始日listwheel
    hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
    //添加数据
    for(i = 0;i < GUI_COUNTOF(_apDay);i++)
    {
        LISTWHEEL_AddString(hItem,*(_apDay+i));
    }

    //设置终止年listwheel
    hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
    //添加数据
    for(i = 0;i < GUI_COUNTOF(_apYear);i++)
    {
        LISTWHEEL_AddString(hItem,*(_apYear+i));
    }

    //设置终止月listwheel
    hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
    //添加数据
    for(i = 0;i < GUI_COUNTOF(_apMonth);i++)
    {
        LISTWHEEL_AddString(hItem,*(_apMonth+i));
    }

    //设置终止日listwheel
    hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
    //添加数据
    for(i = 0;i < GUI_COUNTOF(_apDay);i++)
    {
        LISTWHEEL_AddString(hItem,*(_apDay+i));
    }
    //初始化multiedit
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
    MULTIEDIT_SetText(hItem, "alarm log\n1\n2\n3\n4\n\n\n\n\n\nn\\2\n\3\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\alarm log");
    MULTIEDIT_SetInsertMode(hItem, 1);
    SCROLLBAR_CreateAttached(hItem, SCROLLBAR_CF_VERTICAL);//创建垂直滑轮
    SCROLLBAR_CreateAttached(hItem, 0);//创建水平滑轮
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SCROLLBAR_0: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SCROLLBAR_1: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        //获取句柄
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
        //获取当前句柄索引
        list_start_index[0] = LISTWHEEL_GetPos(hItem);
        //设置当前句柄数据项
        LISTWHEEL_SetSel(hItem,list_start_index[0]);
        LISTWHEEL_GetItemText(hItem,list_start_index[0],sel_start_date.year,5);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        //获取句柄
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
        //获取当前句柄索引
        list_start_index[1] = LISTWHEEL_GetPos(hItem);
        //设置当前句柄数据项
        LISTWHEEL_SetSel(hItem,list_start_index[1]);
        LISTWHEEL_GetItemText(hItem,list_start_index[1],sel_start_date.month,5);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'Button'告警记录
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'Button'充电记录
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        //CreateChargeLog();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_2: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        //获取句柄
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
        //获取当前句柄索引
        list_start_index[2] = LISTWHEEL_GetPos(hItem);
        //设置当前句柄数据项
        LISTWHEEL_SetSel(hItem,list_start_index[2]);
        LISTWHEEL_GetItemText(hItem,list_start_index[2],sel_start_date.day,5);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_3: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
        //获取当前句柄索引
        list_end_index[0] = LISTWHEEL_GetPos(hItem);
        //设置当前句柄数据项
        LISTWHEEL_SetSel(hItem,list_end_index[0]);
        LISTWHEEL_GetItemText(hItem,list_end_index[0],sel_end_date.year,5);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_4: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
        //获取当前句柄索引
        list_end_index[1] = LISTWHEEL_GetPos(hItem);
        //设置当前句柄数据项
        LISTWHEEL_SetSel(hItem,list_end_index[1]);
        LISTWHEEL_GetItemText(hItem,list_end_index[1],sel_end_date.month,5);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_LISTWHEEL_5: // Notifications sent by 'Listwheel'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_SEL_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
        //获取当前句柄索引
        list_end_index[2] = LISTWHEEL_GetPos(hItem);
        //设置当前句柄数据项
        LISTWHEEL_SetSel(hItem,list_end_index[2]);
        LISTWHEEL_GetItemText(hItem,list_end_index[2],sel_end_date.day,5);
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateAlarmLog
*/
WM_HWIN CreateAlarmLog(void);
WM_HWIN CreateAlarmLog(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}
// USER START (Optionally insert additional public code)
void PutOut_Alarm_Log()
{
    CreateAlarmLog();
    while(1)
    {
        dispbmp("system/dpc.bmp", 0, 5, 5, 1, 1);
        GUI_Delay(10);
    }
}
// USER END

/*************************** End of file ****************************/
