
/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "touchtimer.h"
// USER END

#include "DIALOG.h"

#include "includes.h"

#include "order.h"
#include "interface.h"
#include "utils.h"
#include "cJSON.h"
#include "evse_config.h"
#include "cfg_parse.h"
#include "stringName.h"
#include "errorcode.h"
#include <string.h>

#define BYTES_LEN 1024

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
// USER START (Optionally insert additional defines)
#define ID_IMAGE_0    (GUI_ID_USER + 0x1C)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)

#define ID_BUTTON_0  (GUI_ID_USER + 0x00)//信息
#define ID_BUTTON_1  (GUI_ID_USER + 0x01)//历史
#define ID_BUTTON_2  (GUI_ID_USER + 0x02)//系统
#define ID_BUTTON_3  (GUI_ID_USER + 0x03)//退出
#define ID_BUTTON_4  (GUI_ID_USER + 0x04)//模拟
#define ID_BUTTON_5  (GUI_ID_USER + 0x05)//状态
#define ID_TEXT_5  (GUI_ID_USER + 0x06)//
#define ID_EDIT_0  (GUI_ID_USER + 0x07)//
#define ID_TEXT_6  (GUI_ID_USER + 0x08)//

#define ID_LISTWHEEL_0  (GUI_ID_USER + 0x10)
#define ID_LISTWHEEL_1  (GUI_ID_USER + 0x11)
#define ID_LISTWHEEL_2  (GUI_ID_USER + 0x12)
#define ID_LISTWHEEL_3  (GUI_ID_USER + 0x13)
#define ID_LISTWHEEL_4  (GUI_ID_USER + 0x14)
#define ID_LISTWHEEL_5  (GUI_ID_USER + 0x15)
#define ID_MULTIEDIT_0  (GUI_ID_USER + 0x16)
#define ID_LISTVIEW_0   (GUI_ID_USER + 0x17)

#define ID_TimerTime    1
#define ID_TimerFlush   2
#define ID_TimerSignal  3

#define ALARM_COLUMNS   4
#define CHARGE_COLUMNS  20
#define DB_DEBUG    0
//6 12 10
//1 2 1 2 1 2
//static uint8_t _alarmLog[] = {
//    "序号      开始时间            结束时间          告警内容\n\
// 01  2017-06-07 12:13:34  2017-06-08 12:13:23  急停故障"
//};
// USER END
static WM_HWIN _hWinManagerAlarmLog;
static WM_HTIMER _timerRTC,_timerData,_timerSignal;
uint16_t column_num,row_num;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static const char *_apYear[] =
{
    "2017", "2018", "2019", "2020", "2021", 
    "2022", "2023", "2024", "2025", "2026", 
    "2027", "2028", "2029", "2030", "2031",
    "2032", "2033", "2034", "2035", "2036", 
    "2037", "2038", "2039", "2040", "2041", 
    "2042", "2043", "2044",     
};
static const char *_apMonth[]=
{
    "01","02","03","04","05","06",
    "07","08","09","10","11","12",
};
static const char *_apDay[]=
{
    "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12",
    "13", "14", "15", "16", "17", "18",
    "19", "20", "21", "22", "23", "24",
    "25", "26", "27", "28", "29", "30", "31",
};
typedef struct
{
    int tm_year;
    int tm_mon;
    int tm_mday;
}_MANAGERDate;
static DateStruct sel_start_date = {"2004","01","01"};
static DateStruct sel_end_date = {"2004","01","01"};
static uint8_t list_start_index[3];
static uint8_t list_end_index[3];

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
    { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 789, 459, 0, 0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 630, 0, 80, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 720, 0, 70, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 440, 0, 180, 16, 0, 0x0, 0 },//网络信号强度
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 225, 367, 300, 20, 0, 0x0, 0 },//最底端的说明
    { BUTTON_CreateIndirect, "信息查询", ID_BUTTON_0, 50, 70, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "历史记录", ID_BUTTON_1, 50, 140, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "系统配置", ID_BUTTON_2, 50, 210, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "退    出", ID_BUTTON_3, 50, 280, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "模拟量", ID_BUTTON_4, 550, 20, 80, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "状态量", ID_BUTTON_5, 550, 52, 80, 30, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_0, 290, 25, 43, 50, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_1, 340, 25, 20, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Date", ID_TEXT_5, 243, 40, 50, 31, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_2, 365, 25, 20, 50, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_3, 450, 25, 43, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "TO", ID_TEXT_6, 400, 40, 50, 20, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_4, 500, 25, 20, 50, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_5, 525, 25, 20, 50, 0, 0x0, 0 },
//    { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 210, 82, 560, 276, 0, 0x0, 0 },
    { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 210, 82, 560, 276, 0, 0x0, 0 },//560,276
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
int  Data_Flush(uint8_t log_type,WM_HWIN hItem)
{
    cJSON *jsParent;
    cJSON *jsChild;
    cJSON *jsItem;
    cJSON *jsItemTmp;
    ErrorCode_t errcode;
    uint32_t ulMaxItem;
    int i = 0,j = 0;
	struct tm *ts;
//	struct tm *ts_start;
//	struct tm *ts_end;
    _MANAGERDate ts_start;
    _MANAGERDate ts_end;
	char buf[80] = "\0";
    
	if(0 == log_type)   //故障记录
    {
        jsParent = GetCfgObj("system\\evse.log", &errcode);
        if (jsParent == NULL)
        {
            cJSON_Delete(jsParent);
            return errcode;
        }
        ulMaxItem  = cJSON_GetArraySize(jsParent);
        if (ulMaxItem == 0)
        {
            cJSON_Delete(jsParent);
            LISTVIEW_AddRow(hItem, NULL);
            LISTVIEW_SetItemText(hItem, 0, 0, "没有记录");

            return 0;
        }

        ts_start.tm_year = (sel_start_date.year[0]-48)*1000+
            (sel_start_date.year[1]-48)*100+
            (sel_start_date.year[2]-48)*10+
            (sel_start_date.year[3]-48);
        ts_start.tm_mon = (sel_start_date.month[0]-48)*10+
            (sel_start_date.month[1]-48);
        ts_start.tm_mday = (sel_start_date.day[0]-48)*10+
            (sel_start_date.day[1]-48);

        ts_end.tm_year = (sel_end_date.year[0] - 48) * 1000 +
            (sel_end_date.year[1]-48) * 100 +
            (sel_end_date.year[2]-48) * 10 +
            (sel_end_date.year[3]-48);
        ts_end.tm_mon = (sel_end_date.month[0]-48) * 10 +
            (sel_end_date.month[1]-48);
        ts_end.tm_mday = (sel_end_date.day[0]-48) * 10 +
            (sel_end_date.day[1]-48);

        for (j = 0; j < ulMaxItem; j++)
        {
            jsChild = cJSON_GetArrayItem(jsParent, j);

            jsItem = cJSON_GetObjectItem(jsChild, jnLogTime);
	        ts = localtime((time_t*)&(jsItem->valueint));

            //判断起始年
            if((ts->tm_year+1900) < ts_start.tm_year)
            {
                continue;
            }
            else if((ts->tm_year+1900) == ts_start.tm_year)
            {
                if((ts->tm_mon+1) < ts_start.tm_mon)
                {
                    continue;
                }
                else if((ts->tm_mon+1) == ts_start.tm_mon)
                {
                    if(ts->tm_mday < ts_start.tm_mday)
                    {
                        continue;
                    }
                }
            }
            //判断截止年
            if((ts->tm_year+1900) > ts_end.tm_year)
            {
                continue;
            }
            else if((ts->tm_year+1900) == ts_end.tm_year)
            {
                if((ts->tm_mon+1) > ts_end.tm_mon)
                {
                    continue;
                }
                else if((ts->tm_mon+1) == ts_end.tm_mon)
                {
                    if(ts->tm_mday > ts_end.tm_mday)
                    {
                        continue;
                    }
                }
            }

            i++;

            //序号 记录时间  枪号  故障等级  故障状态  故障信息
            LISTVIEW_AddRow(hItem, NULL);

            sprintf((char *)buf, "%d", i);
            LISTVIEW_SetItemText(hItem, 0, i, buf);

            jsItem = cJSON_GetObjectItem(jsChild, jnLogTime);
	        ts = localtime((time_t*)&(jsItem->valueint));
	        strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", ts);
            LISTVIEW_SetItemText(hItem, 1, i, buf);

            jsItem = cJSON_GetObjectItem(jsChild, jnLogDevice);
            sprintf((char *)buf, "%d", jsItem->valueint);
            LISTVIEW_SetItemText(hItem, 2, i, buf);

            //0 状态 1 告警 2 异常 3 故障
            jsItem = cJSON_GetObjectItem(jsChild, jnLogLevel);
            switch (jsItem->valueint)
            {
                case 0:
                    LISTVIEW_SetItemText(hItem, 3, i, "状态");
                    break;
                case 1:
                    LISTVIEW_SetItemText(hItem, 3, i, "告警");
                    break;
                case 2:
                    LISTVIEW_SetItemText(hItem, 3, i, "异常");
                    break;
                case 3:
                    LISTVIEW_SetItemText(hItem, 3, i, "故障");
                    break;
            }

            jsItem = cJSON_GetObjectItem(jsChild, jnLogState);
            switch (jsItem->valueint)
            {
                case 0:
                    LISTVIEW_SetItemText(hItem, 4, i, "消除");
                    break;
                case 1:
                    LISTVIEW_SetItemText(hItem, 4, i, "发生");
                    break;
            }

            jsItem = cJSON_GetObjectItem(jsChild, jnLogMessage);
            LISTVIEW_SetItemText(hItem, 5, i, jsItem->valuestring);
        }
        if (i == 0)
        {
            LISTVIEW_AddRow(hItem, NULL);
            LISTVIEW_SetItemText(hItem, 0, 0, "没有记录");            
        }
    }
    else if(1 == log_type)
    {
        jsParent = GetCfgObj("system\\order.txt", &errcode);
        if (jsParent == NULL)
        {
            cJSON_Delete(jsParent);
            return errcode;
        }
        ulMaxItem  = cJSON_GetArraySize(jsParent);
        if (ulMaxItem == 0)
        {
            cJSON_Delete(jsParent);
            LISTVIEW_AddRow(hItem, NULL);
            LISTVIEW_SetItemText(hItem, 0, 0, "没有记录");
            return 0;
        }

        ts_start.tm_year = (sel_start_date.year[0] - 48) * 1000 +
            (sel_start_date.year[1] - 48) * 100 +
            (sel_start_date.year[2] - 48) * 10 +
            (sel_start_date.year[3] - 48);
        ts_start.tm_mon = (sel_start_date.month[0] - 48) * 10 +
            (sel_start_date.month[1] - 48);
        ts_start.tm_mday = (sel_start_date.day[0] - 48) * 10 +
            (sel_start_date.day[1] - 48);

        ts_end.tm_year = (sel_end_date.year[0] - 48) * 1000 +
            (sel_end_date.year[1] - 48) * 100 +
            (sel_end_date.year[2] - 48) * 10 +
            (sel_end_date.year[3] - 48);
        ts_end.tm_mon = (sel_end_date.month[0] - 48) * 10 +
            (sel_end_date.month[1] - 48);
        ts_end.tm_mday = (sel_end_date.day[0] - 48) * 10 +
            (sel_end_date.day[1] - 48);

        for (j = 0; j < ulMaxItem; j++)
        {

            jsChild = cJSON_GetArrayItem(jsParent, j);

            jsItem = cJSON_GetObjectItem(jsChild, jnOrderStartTime);
	        ts = localtime((time_t*)&(jsItem->valueint));

            //判断起始年
            if((ts->tm_year+1900) < ts_start.tm_year)
            {
                continue;
            }
            else if((ts->tm_year+1900) == ts_start.tm_year)
            {
                if((ts->tm_mon+1) < ts_start.tm_mon)
                {
                    continue;
                }
                else if((ts->tm_mon+1) == ts_start.tm_mon)
                {
                    if(ts->tm_mday < ts_start.tm_mday)
                    {
                        continue;
                    }
                }
            }
            //判断截止年
            if((ts->tm_year+1900) > ts_end.tm_year)
            {
                continue;
            }
            else if((ts->tm_year+1900) == ts_end.tm_year)
            {
                if((ts->tm_mon+1) > ts_end.tm_mon)
                {
                    continue;
                }
                else if((ts->tm_mon+1) == ts_end.tm_mon)
                {
                    if(ts->tm_mday > ts_end.tm_mday)
                    {
                        continue;
                    }
                }
            }

            i++;

            /*序号    启动方式    卡号  订单流水号   起始时间    结束时间   结束类型 总电量 总电费 总服务费 总费用 支付方式*/
            LISTVIEW_AddRow(hItem, NULL);
            sprintf((char *)buf, "%d", i);
            LISTVIEW_SetItemText(hItem, 0, i, buf);


            jsItem = cJSON_GetObjectItem(jsChild, jnOrderStartType);
            if(jsItem->valueint == 4)
            {
                LISTVIEW_SetItemText(hItem, 1, i, "刷卡");
            }
            else
            {
                LISTVIEW_SetItemText(hItem, 1, i, "扫码");
            }

	        jsItem = cJSON_GetObjectItem(jsChild, jnCardID);
            LISTVIEW_SetItemText(hItem, 2, i, jsItem->valuestring);


            jsItem = cJSON_GetObjectItem(jsChild, jnOrderOrderSN);
            LISTVIEW_SetItemText(hItem, 3, i, jsItem->valuestring);


            jsItem = cJSON_GetObjectItem(jsChild, jnOrderStartTime);
	        ts = localtime((time_t*)&(jsItem->valueint));
	        strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", ts);
            LISTVIEW_SetItemText(hItem, 4, i, buf);

	        jsItem = cJSON_GetObjectItem(jsChild, jnOrderStopTime);
	        ts = localtime((time_t*)&(jsItem->valueint));
	        strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", ts);
            LISTVIEW_SetItemText(hItem, 5, i, buf);

            jsItem = cJSON_GetObjectItem(jsChild, jnOrderStopType);
            printf_safe("StopType\t%d\n", jsItem->valueint);
            switch(jsItem->valueint)
            {
                case defOrderStopType_RFID:
                    LISTVIEW_SetItemText(hItem, 6, i, "刷卡结束");
                    break;
                case defOrderStopType_Remote:
                    LISTVIEW_SetItemText(hItem, 6, i, "远程结束");
                    break;
                case defOrderStopType_Full:
                    LISTVIEW_SetItemText(hItem, 6, i, "充满结束");
                    break;
                case defOrderStopType_Fee:
                    LISTVIEW_SetItemText(hItem, 6, i, "达到充电金额");
                    break;
                case defOrderStopType_Scram:
                case defOrderStopType_NetLost:
                case defOrderStopType_Poweroff:
                case defOrderStopType_OverCurr:
                case defOrderStopType_Knock:
                    LISTVIEW_SetItemText(hItem, 6, i, "异常结束");
                    break;
                default:
                    LISTVIEW_SetItemText(hItem, 6, i, "未知原因结束");
                    break;
            }

            jsItem = cJSON_GetObjectItem(jsChild,jnOrderStopPower);
            jsItemTmp = cJSON_GetObjectItem(jsChild,jnOrderStartPower);
            sprintf((char *)buf,"%.2lf",(jsItem->valuedouble - jsItemTmp->valuedouble)*100 / 100.0);
            LISTVIEW_SetItemText(hItem, 7, i, buf);

            jsItem = cJSON_GetObjectItem(jsChild, jnOrderTotalPowerFee);
            sprintf((char *)buf,"%.2lf",jsItem->valuedouble * 100 / 100.0);
            LISTVIEW_SetItemText(hItem, 8, i, buf);

            jsItemTmp = cJSON_GetObjectItem(jsChild, jnOrderTotalServFee);
            sprintf((char *)buf,"%.2lf",jsItemTmp->valuedouble * 100 / 100.0);
            LISTVIEW_SetItemText(hItem, 9, i, buf);

            sprintf((char *)buf,"%.2lf",(jsItem->valuedouble + jsItemTmp->valuedouble) * 100 / 100.0);
            LISTVIEW_SetItemText(hItem, 10, i, buf);

            jsItemTmp = cJSON_GetObjectItem(jsChild, jnOrderPayStatus);
            if(jsItem->valueint == 0)
            {
                LISTVIEW_SetItemText(hItem, 11, i, "刷卡支付");
            }
            else
            {
                LISTVIEW_SetItemText(hItem, 11, i, "扫码支付");
            }

        }
        if (i == 0)
        {
            LISTVIEW_AddRow(hItem, NULL);
            LISTVIEW_SetItemText(hItem, 0, 0, "没有记录");            
        }
    }

    cJSON_Delete(jsParent);

    return errcode;
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    volatile WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;
    uint16_t     i,_strNum[3];
	volatile HEADER_Handle hHeader;
	char    buf[20];
//	static char  Value = 0;
    SCROLLBAR_Handle hScroll;
    SCROLLBAR_Handle wScroll;
//    static int _x,_y;
//    WM_SCROLL_STATE ScrollState;

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        WM_SetFocus(_hWinManagerAlarmLog);
        /// TODO (zshare#1#): 下面的if不起作用.\
        但是if里嵌套的if起作用,目前先用此来规避不起作用的if
        if(_hWinManagerAlarmLog == cur_win)
        {
            /**< 数据处理 */
            //Data_Process(pMsg);
            /**< 信号数据处理 */
            Signal_Show();
            /**< 灯光控制 */
            Led_Show();
            /**< 如果界面发生了切换 */
            if(_hWinManagerAlarmLog == cur_win)
            {
                /**< 故障分析 */
                //Err_Analy(pMsg->hWin);
                /**< 特殊触控点分析 */
                CaliDone_Analy(pMsg->hWin);
            }
        }
        break;
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        FrameWin_Init(pMsg, ID_TEXT_1, ID_TEXT_2, ID_TEXT_3, ID_TEXT_4,ID_IMAGE_0);
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_5),&SIF16_Font,GUI_BLACK,"起始");
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6),&SIF16_Font,GUI_BLACK,"终止");
        //
        // Initialization of 'Button'
        //
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &SIF36_Font,BUTTON_CI_UNPRESSED,GUI_GREEN,BUTTON_CI_UNPRESSED,GUI_BLACK,"信息查询");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &SIF36_Font,BUTTON_CI_UNPRESSED,GUI_RED,BUTTON_CI_UNPRESSED,GUI_RED,"历史查询");
        BUTTON_SetPressed(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),1);
        BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_PRESSED,GUI_RED);

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &SIF36_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"系统配置");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &SIF36_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"退    出");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &SIF16_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"查询告警");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &SIF16_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"查询充电");
        //
        // Initialization of 'Listwheel'
        //
        //初始化listwheel
        for(i = 0;i < 6;i++)
        {
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0+i);
            //设置字体
            LISTWHEEL_SetFont(hItem,&GUI_FontComic18B_ASCII);
            LISTWHEEL_SetTextAlign(hItem,GUI_TA_VCENTER | GUI_TA_VERTICAL);
            //设置吸附位置
            LISTWHEEL_SetSnapPosition(hItem,15);
            //设置绘制数据项所使用的行高
        //        LISTWHEEL_SetLineHeight(hItem,30);
            //设置选中的条目的文本颜色
            LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_RED);
            LISTWHEEL_SetVelocity(hItem, 100);
        }
        //设置起始年listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
        //绘制指示行
        //    LISTWHEEL_SetOwnerDraw(hItem,ListWheel0_OwnerDraw);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apYear);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apYear+i));
        }

        //设置起始月listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apMonth);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apMonth+i));
        }

        //设置起始日listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apDay);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apDay+i));
        }

        //设置终止年listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apYear);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apYear+i));
        }

        //设置终止月listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apMonth);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apMonth+i));
        }

        //设置终止日listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apDay);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apDay+i));
        }
//        //初始化multiedit
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
//        MULTIEDIT_SetAutoScrollH(hItem,1);
//        MULTIEDIT_SetAutoScrollV(hItem,1);
//        MULTIEDIT_SetInsertMode(hItem, 1);
//        MULTIEDIT_SetFont(hItem, &SIF24_Font);
//        MULTIEDIT_SetCursorOffset(hItem,0);
//        MULTIEDIT_EnableBlink(hItem,0,0);
//        //memset(_alarmLog,'\0',strlen(_alarmLog));
//        MULTIEDIT_SetText(hItem, " ");
////        SCROLLBAR_CreateAttached(hItem, SCROLLBAR_CF_VERTICAL);//创建垂直滑轮
////        SCROLLBAR_CreateAttached(hItem, 0);//创建水平滑轮
			//
			// 初始列表控件
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
			/* 设置列表控件中header控件的所显示文本的字体 */
			hHeader = LISTVIEW_GetHeader(hItem);
			HEADER_SetFont(hHeader, &SIF16_Font);
//            LISTVIEW_SetAutoScrollH(hItem,1);
//            LISTVIEW_SetAutoScrollV(hItem,1);

            /*srollbar*/
            hScroll = SCROLLBAR_CreateAttached(hItem, 0);//水平滑轮
            SCROLLBAR_SetNumItems(hScroll, 30 * 4);
            SCROLLBAR_SetWidth(hScroll,20);
            wScroll = SCROLLBAR_CreateAttached(hItem, SCROLLBAR_CF_VERTICAL);//垂直滑轮
            SCROLLBAR_SetNumItems(wScroll, 30 * 20);
            SCROLLBAR_SetWidth(wScroll,20);
            /*end*/

            //SCROLLBAR_SetDefaultWidth(15);
			/* 设置列表控件选项中所显示文本的字体 */
			LISTVIEW_SetFont(hItem, &SIF16_Font);
			/* 设置列表控件表格可见 */
			LISTVIEW_SetGridVis(hItem, 1);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {
            /*scrollbar*/
//        case GUI_ID_HSCROLL:
//            if(NCode == WM_NOTIFICATION_VALUE_CHANGED)
//            {
//                   /* 得到滚动条的状态，得到的数值好像是负值 才能使得 _x - ScrollState.v是正值 */
//                    WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
//                    if (_x != ScrollState.v)
//                    {
//                        WM_MoveWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), _x - ScrollState.v, 0);
//                        _x = ScrollState.v;
//                    }
//            }
//            else if(NCode == GUI_ID_VSCROLL)
//            {
//                    WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
//                    if (_y != ScrollState.v)
//                    {
//                        WM_MoveWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),0, _y - ScrollState.v);
//                        _y = ScrollState.v;
//                    }
//            }
//            break;
            /*end*/
        case ID_BUTTON_0: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            /**< 跳转到模拟量信息查询 */
            _deleteWin(_hWinManagerAlarmLog);
            CreateManagerInfoAnalog();
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_1: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_2: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            /**< 跳转到设置参数信息查询 */
            _deleteWin(_hWinManagerAlarmLog);
            CreateManagerSysSet();
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_3: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            //WM_DeleteWindow(pMsg->hWin);
            //PutOut_SelAOrB();
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            /**< 跳转至home */
            _deleteWin(_hWinManagerAlarmLog);
            CreateHome();
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_4: //查询故障 Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            /**< get到现有表格的行列数 */
            column_num = LISTVIEW_GetNumColumns(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
            row_num = LISTVIEW_GetNumRows(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
            for(i = 0;i < column_num;i++)
            {
                LISTVIEW_DeleteColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),0);
            }
            for (i = 0; i < row_num; i++)
            {
//                LISTVIEW_DeleteRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0);
            }

            /*序号 记录时间  枪号  故障等级  故障状态  故障信息*/
			/* 添加四列表，调用一次函数LISTVIEW_AddColumn添加一列 */
            LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "序号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "记录时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 60, "设备", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "故障等级", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "故障状态", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "故障信息", GUI_TA_HCENTER | GUI_TA_VCENTER);

			/* 添加三行，调用一次函数LISTVIEW_AddRow添加一行 */
//			LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);
//			LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);
//			LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);


            Data_Flush(0,WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
//            for(i = 0; i< 500;i++)
//            {
//                LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);
//                sprintf(buf, "%03d", i+1);
//                //序号
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, i, buf);
////                memset(buf,'\0',strlen(buf));
//                strcpy(buf, "2016-07-07 12:13:14");
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, i, buf);
////                memset(buf,'\0',strlen(buf));
//                strcpy(buf, "2016-07-07 12:13:14");
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, i, buf);
////                memset(buf,'\0',strlen(buf));
//                strcpy(buf, "i");
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, i, buf);
//            }

			/* 为列表控件三行四列共12个选项全部添加文本 */
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, "00");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, 0, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, 0, "2016-07-07 12:14:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, 0, "急停故障");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 1, "01");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, 1, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, 1, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, 1, "交流过压");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 2, "02");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, 2, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, 2, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, 2, "继电器故障");
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_5: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            column_num = LISTVIEW_GetNumColumns(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
            row_num = LISTVIEW_GetNumColumns(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
            for(i = 0;i < column_num;i++)
            {
                LISTVIEW_DeleteColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),0);
            }
            for (i = 0; i < row_num; i++)
            {
//                LISTVIEW_DeleteRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), i);                  
            }
            /*序号    启动方式    卡号  订单流水号   起始时间    结束时间   结束类型 总电量 总电费 总服务费 总费用 支付方式*/
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "序号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 60, "启动方式", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "卡号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 240, "订单流水号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "起始时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "结束时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "结束类型", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "总电量", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "总电费", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "总服务费", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "总费用", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "支付方式", GUI_TA_HCENTER | GUI_TA_VCENTER);
            Data_Flush(1,WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));

            break;
        /// TODO (zshare#1#): ///因为鼠标重置的问题, \
        所以需要用到WM_NOTIFICATION_MOVED_OUT事件,不触发WM_NOTIFICATION_RELEASED
          case WM_NOTIFICATION_RELEASED://WM_NOTIFICATION_MOVED_OUT:
            /**< 跳转到状态信息查询 */
//            _deleteWin(_hWinManagerInfoAnalog);
//            CreateManagerInfoStatus();
            break;
          }
            break;
        case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            //获取句柄
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
            //获取当前句柄索引
            list_start_index[0] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_start_index[0]);
            LISTWHEEL_GetItemText(hItem,list_start_index[0],sel_start_date.year,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            //获取句柄
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
            //获取当前句柄索引
            list_start_index[1] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_start_index[1]);
            LISTWHEEL_GetItemText(hItem,list_start_index[1],sel_start_date.month,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_2: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            //获取句柄
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
            //获取当前句柄索引
            list_start_index[2] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_start_index[2]);
            LISTWHEEL_GetItemText(hItem,list_start_index[2],sel_start_date.day,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_3: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
            //获取当前句柄索引
            list_end_index[0] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_end_index[0]);
            LISTWHEEL_GetItemText(hItem,list_end_index[0],sel_end_date.year,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_4: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
            //获取当前句柄索引
            list_end_index[1] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_end_index[1]);
            LISTWHEEL_GetItemText(hItem,list_end_index[1],sel_end_date.month,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_5: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
            //获取当前句柄索引
            list_end_index[2] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_end_index[2]);
            LISTWHEEL_GetItemText(hItem,list_end_index[2],sel_end_date.day,5);
            // USER END
            break;
        }
        break;
    }
    case WM_TIMER:
        if(pMsg->Data.v == _timerRTC)
        {
            /**< 显示时间和日期 */
            Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), strCSQ);
            /**< 重启定时器 */
            WM_RestartTimer(pMsg->Data.v, 20);
        }
        if(pMsg->Data.v == _timerSignal)
        {
            WM_RestartTimer(pMsg->Data.v, 2000);
        }
        if(pMsg->Data.v == _timerData)
        {
            //Data_Flush(pMsg);
            WM_RestartTimer(pMsg->Data.v,5000);
        }
        break;
    case MSG_CREATERRWIN:
        /**< 故障界面不存在则创建,存在则刷新告警 */
        err_window(pMsg->hWin);
        break;
    case MSG_DELERRWIN:
        /**< 故障界面存在则删除故障界面 */
        if(bittest(winCreateFlag,0))
        {
            bitclr(winCreateFlag,0);
            GUI_EndDialog(err_hItem,0);
            err_hItem = 0;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/

/** @brief
 *  输出管理员界面里的信息查询告警记录部分
 * @param
 * @param
 * @return
 *       CreateManagerAlarmLog
*/
WM_HWIN CreateManagerAlarmLog(void)
{
    _hWinManagerAlarmLog = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    cur_win = _hWinManagerAlarmLog;
    _timerRTC = WM_CreateTimer(WM_GetClientWindow(_hWinManagerAlarmLog), ID_TimerTime, 20, 0);
    _timerData = WM_CreateTimer(WM_GetClientWindow(_hWinManagerAlarmLog), ID_TimerFlush,1000,0);
    _timerSignal = WM_CreateTimer(WM_GetClientWindow(_hWinManagerAlarmLog), ID_TimerSignal,5000,0);
    return 0;
}
/*************************** End of file ****************************/



