/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "xbffontcreate.h"
#include "touchtimer.h"
#include "SCROLLBAR.h"
// USER END

#include "DIALOG.h"
/*******************************************************************
*
*       defines
*
********************************************************************
*/
/*编辑窗口14行1列，状态项14个*/
#define EDIT_MAX_X 1
#define EDIT_MAX_Y 14
#define STATUE_LINE 14
#define STATUE_CAL 1
//后续将编辑和文本的滚轮方式用链表进行封装
static EDIT_Handle _aahEdit[EDIT_MAX_Y][EDIT_MAX_X];
static TEXT_Handle _aahText[STATUE_LINE][STATUE_CAL];
static int _x,_y;

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_IMAGE_0     (GUI_ID_USER + 0x1C)
// USER START (Optionally insert additional defines)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)

#define ID_BUTTON_0  (GUI_ID_USER + 0x00)//信息
#define ID_BUTTON_1  (GUI_ID_USER + 0x01)//历史
#define ID_BUTTON_2  (GUI_ID_USER + 0x02)//系统
#define ID_BUTTON_3  (GUI_ID_USER + 0x03)//退出
#define ID_BUTTON_4  (GUI_ID_USER + 0x04)//模拟
#define ID_BUTTON_5  (GUI_ID_USER + 0x05)//状态
#define ID_TEXT_5  (GUI_ID_USER + 0x06)//
#define ID_EDIT_0  (GUI_ID_USER + 0x07)//
#define ID_TEXT_6  (GUI_ID_USER + 0x08)//
#define ID_TEXT_7  (GUI_ID_USER + 0x09)//
#define ID_TEXT_8  (GUI_ID_USER + 0x0A)//
#define ID_TEXT_9  (GUI_ID_USER + 0x0F)//
#define ID_TEXT_10  (GUI_ID_USER + 0x10)//
#define ID_TEXT_11  (GUI_ID_USER + 0x11)//
#define ID_EDIT_1  (GUI_ID_USER + 0x12)//
#define ID_EDIT_2  (GUI_ID_USER + 0x13)//
#define ID_EDIT_3  (GUI_ID_USER + 0x14)//
#define ID_EDIT_4  (GUI_ID_USER + 0x15)//
#define ID_EDIT_5  (GUI_ID_USER + 0x16)//
#define ID_EDIT_6  (GUI_ID_USER + 0x17)//

#define ID_TimerTime    0
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
// USER END
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
    { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 789, 459, 0, 0, 0 },
    // USER START (Optionally insert additional widgets)
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 630, 0, 80, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 720, 0, 70, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 540, 0, 90, 16, 0, 0x0, 0 },//网络信号强度
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 225, 367, 300, 20, 0, 0x0, 0 },//最底端的说明
    { BUTTON_CreateIndirect, "信息查询", ID_BUTTON_0, 70, 120, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "历史记录", ID_BUTTON_1, 70, 184, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "系统配置", ID_BUTTON_2, 70, 247, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "退    出", ID_BUTTON_3, 70, 312, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "模拟量", ID_BUTTON_4, 285, 40, 140, 40, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "状态量", ID_BUTTON_5, 491, 40, 140, 40, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "交流电压:", ID_TEXT_5, 300, 100, 150, 30, 0, 0x0, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 477, 100, 100, 30, 0, 0x64, 0 },
//    { TEXT_CreateIndirect, "交流电流:", ID_TEXT_6, 300, 140, 150, 30, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "充电导引电压:", ID_TEXT_7, 300, 178, 160, 30, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "频    率:", ID_TEXT_8, 300, 216, 150, 30, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "A插座温度:", ID_TEXT_9, 300, 256, 150, 30, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "B插座温度:", ID_TEXT_10, 300, 296, 150, 30, 0, 0x0, 0 },
//    { TEXT_CreateIndirect, "接线温度:", ID_TEXT_11, 300, 336, 150, 30, 0, 0x0, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 477, 140, 100, 30, 0, 0x64, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 477, 178, 100, 30, 0, 0x64, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 477, 216, 100, 30, 0, 0x64, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 477, 256, 100, 30, 0, 0x64, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_5, 477, 296, 100, 30, 0, 0x64, 0 },
//    { EDIT_CreateIndirect, "Edit", ID_EDIT_6, 477, 336, 100, 30, 0, 0x64, 0 },
    // USER END
};
// USER START (Optionally insert additional static code)
// USER END
static void Timer_Process(WM_MESSAGE *pMsg)
{
    uint8_t i = 0;
    WM_HWIN hWin = pMsg->hWin;

    Caculate_RTC_Show(pMsg,ID_TEXT_1,ID_TEXT_2);
    //需要增加3G模块的信号强度判断
    switch(i % 5)
    {
    case 0:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:非常强");
        break;
    case 1:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:一般");
        break;
    case 2:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:差");
        break;
    case 3:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:极差");
        break;
    default:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:无");
        break;
    }

    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),&XBF24_Font,"220.0V");
    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),&XBF24_Font,"32.00A");
    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2),&XBF24_Font,"12.00V");
    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3),&XBF24_Font,"50Hz");
    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_4),&XBF24_Font,"30.0℃");
    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_5),&XBF24_Font,"30.0℃");
    Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_6),&XBF24_Font,"30.0℃");

}
/*******************************************************************
*
*       _cbWindow

  The callback moves the edit-fiels when a notification message
  was send.
*/
static void _cbWindow(WM_MESSAGE *pMsg) {
  WM_SCROLL_STATE ScrollState;
  WM_HWIN      hItem;
  char *dest = (char *)malloc(10);
  static int flag = 0;
  switch (pMsg->MsgId) {
  case WM_NOTIFY_PARENT:
    if (pMsg->Data.v == WM_NOTIFICATION_VALUE_CHANGED) {
      if (WM_GetId(pMsg->hWinSrc) == GUI_ID_HSCROLL) {
		/* 得到滚动条的状态，得到的数值好像是负值 才能使得 _x - ScrollState.v是正值 */
        WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
        if (_x != ScrollState.v) {
          int x, y;
          for (y = 0; y < EDIT_MAX_Y; y++) {
            for (x = 0; x < EDIT_MAX_X; x++) {
              WM_MoveWindow(_aahEdit[y][x], _x - ScrollState.v, 0);
            }
          }
          _x = ScrollState.v;
        }
      }
      else if(WM_GetId(pMsg->hWinSrc) == GUI_ID_VSCROLL)
      {
        WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
        if (_y != ScrollState.v) {
          int x, y;
          for (y = 0; y < EDIT_MAX_Y; y++) {
            for (x = 0; x < EDIT_MAX_X; x++) {
              WM_MoveWindow(_aahEdit[y][x],0, _y - ScrollState.v);
            }
          }
          _y = ScrollState.v;
        }
      }
      else
      {
          EDIT_SetText(_aahEdit[2][4],"adsfa");
          flag = EDIT_GetValue(_aahEdit[2][3]);
          EDIT_GetText(_aahEdit[2][4],dest,10);
          flag = EDIT_GetValue(_aahEdit[2][3]);
        //flag = WM_GetId(pMsg->hWinSrc);
      }
    }
//    else
//    {
//        flag = pMsg->Data.v;
//    }
    break;
  case WM_PAINT:
    GUI_SetBkColor(GUI_WHITE);//绘制编辑内容框的背景颜色
    GUI_Clear();
    break;
  default:
    WM_DefaultProc(pMsg);
  }
}
/*******************************************************************
*
*       _DemoScrollbarMove

  This function creates the window and his child objects. Then it
  runs into a idle-loop, so that the window manager can handle the
  objects.


*/
//static void _DemoScrollbarMove(void) {
//  int x, y;
//  WM_HWIN hWindow;
//  SCROLLBAR_Handle hScroll;
//  SCROLLBAR_Handle wScroll;
//  /* Clear display and display headline */
////  GUI_SetBkColor(GUI_BLUE);
////  GUI_Clear();
////  GUI_SetColor(GUI_WHITE);
////  GUI_SetFont(&GUI_Font24_ASCII);
////  GUI_SetTextAlign(GUI_TA_HCENTER);
////  GUI_DispStringAt("SCROLLBAR_Move - Sample", 160, 5);
////  GUI_SetTextAlign(GUI_TA_LEFT);
////  GUI_SetColor(0xFFFFFF);
////  GUI_SetFont(&GUI_Font8x16);
//
//  /* Create the window */
//  /* 创建窗口 */
//  hWindow = WM_CreateWindow(250, 60, 496, 315, WM_CF_SHOW, &_cbWindow, 0);
//
//  /* Create the scrollbar */
//  /* 创建窗口的子控件 */
//  hScroll = SCROLLBAR_CreateAttached(hWindow, 0);//水平滑轮
//
//  /* Sets the number of items for scrolling */
//  /* 设置滚动条条目的数量 */
//  SCROLLBAR_SetNumItems(hScroll, 48 * EDIT_MAX_X);
//
//  /* Sets the page size */
//  /* 设置页尺寸 */
//  SCROLLBAR_SetPageSize(hScroll, 220);
//
//  //设置垂直滑轮
//  wScroll = SCROLLBAR_CreateAttached(hWindow, SCROLLBAR_CF_VERTICAL);//垂直滑轮
//  /* 设置滚动条条目的数量 */
//  SCROLLBAR_SetNumItems(wScroll, 80 * EDIT_MAX_X);
//
//  /* Sets the page size */
//  /* 设置页尺寸 */
//  SCROLLBAR_SetPageSize(wScroll, 220);
//
//  /* Create the edit-fields */
//  /* 创建编辑区域 */
////  for (y = 0; y < EDIT_MAX_Y; y++) {
////    for (x = 0; x < EDIT_MAX_X; x++) {
////		/* 创建编辑框 */
////      _aahEdit[y][x] = EDIT_CreateAsChild(x * 48, y * 22, 48, 22,
////                                        hWindow, 13, WM_CF_SHOW, 5);
////
////      /* 设置对齐方式和字体 */
////      EDIT_SetTextAlign(_aahEdit[y][x], GUI_TA_RIGHT | GUI_TA_VCENTER);
////      EDIT_SetFont(_aahEdit[y][x], &GUI_Font8x16);
////
////	  /* 句柄 要修改的数值 最大最小值，如果大于0，指定小数点的位置，标志位*/
////	  /* 启用编辑区的十进制编辑模式 给出的数值可以在给定的范围内显示 */
////      EDIT_SetDecMode(_aahEdit[y][x], ((y * EDIT_MAX_X) + x) * 100, -99999, +99999, 2, 0);
////	  }
////  }
//
//  _aahEdit[0][0] = EDIT_CreateEx(0, 0, 48, 22,hWindow,WM_CF_SHOW,0,13,5);
//  _aahEdit[0][1] = EDIT_CreateEx(0,22, 48, 22,hWindow,WM_CF_SHOW,0,13,5);
//  _aahEdit[0][2] = EDIT_CreateEx(480,220, 48, 22,hWindow,WM_CF_SHOW,0,13,5);
//
//
//  for (y = 0; y < EDIT_MAX_Y; y++) {
//    for (x = 0; x < EDIT_MAX_X; x++) {
//      EDIT_SetTextAlign(_aahEdit[y][x], GUI_TA_RIGHT | GUI_TA_VCENTER);
//      EDIT_SetFont(_aahEdit[y][x], &GUI_Font8x16);
//      EDIT_SetDecMode(_aahEdit[y][x], ((y * EDIT_MAX_X) + x) * 100, -99999, +99999, 2, 0);
//    }
//  }
//  /* idle-loop */
//  while (1) {
//    GUI_Exec();
//    GUI_Delay(20);
//  }
//  /* delete window and clear display */
//  WM_DeleteWindow(hWindow);
//  GUI_Clear();
//}


/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;
    int x, y;
    WM_HWIN hWindow;
    SCROLLBAR_Handle hScroll;
    SCROLLBAR_Handle wScroll;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        FrameWin_Init(pMsg, ID_TEXT_1, ID_TEXT_2, ID_TEXT_3, ID_TEXT_4,ID_IMAGE_0);

        // 创建窗口
        hWindow = WM_CreateWindow(250, 140, 496, 260, WM_CF_SHOW, &_cbWindow, 0);
        //创建水平滑轮
        hScroll = SCROLLBAR_CreateAttached(hWindow, 0);//水平滑轮
        //设置滑轮条目数量
        SCROLLBAR_SetNumItems(hScroll, 48 * EDIT_MAX_X);
        //设置页尺寸
        SCROLLBAR_SetPageSize(hScroll, 220);
        //创建垂直滑轮
        wScroll = SCROLLBAR_CreateAttached(hWindow, SCROLLBAR_CF_VERTICAL);//垂直滑轮
        //设置滑轮条目数量
        SCROLLBAR_SetNumItems(wScroll, 80 * EDIT_MAX_Y);
        //设置页尺寸
        SCROLLBAR_SetPageSize(wScroll, 220);

        //创建文本区 -- 24号字体 4-96 5-120 6-144 7-168 8-192
        _aahText[0][0] = TEXT_CreateEx(30, 20, 120, 25,hWindow,WM_CF_SHOW,0,13,"工作状态:");
        _aahText[1][0] = TEXT_CreateEx(30, 50, 120, 25,hWindow,WM_CF_SHOW,0,13,"急停状态:");
        _aahText[2][0] = TEXT_CreateEx(30, 80, 120, 25,hWindow,WM_CF_SHOW,0,13,"环境温度:");
        _aahText[3][0] = TEXT_CreateEx(30, 110, 144, 25,hWindow,WM_CF_SHOW,0,13,"A插座温度:");
        _aahText[4][0] = TEXT_CreateEx(30, 140, 144, 25,hWindow,WM_CF_SHOW,0,13,"B插座温度:");
        _aahText[5][0] = TEXT_CreateEx(30, 170, 168, 25,hWindow,WM_CF_SHOW,0,13,"A枪输出电流:");
        _aahText[6][0] = TEXT_CreateEx(30, 200, 168, 25,hWindow,WM_CF_SHOW,0,13,"B枪输出电流:");
        _aahText[7][0] = TEXT_CreateEx(30, 230, 120, 25,hWindow,WM_CF_SHOW,0,13,"A枪枪锁:");
        _aahText[8][0] = TEXT_CreateEx(30, 260, 120, 25,hWindow,WM_CF_SHOW,0,13,"B枪枪锁:");
        _aahText[9][0] = TEXT_CreateEx(30, 290, 120, 25,hWindow,WM_CF_SHOW,0,13,"交流电压:");
        _aahText[10][0] = TEXT_CreateEx(30, 320, 120, 25,hWindow,WM_CF_SHOW,0,13,"交流电流:");
        _aahText[11][0] = TEXT_CreateEx(30, 350, 144, 25,hWindow,WM_CF_SHOW,0,13,"防雷器状态:");
        _aahText[12][0] = TEXT_CreateEx(30, 380, 144, 25,hWindow,WM_CF_SHOW,0,13,"输出继电器:");
        _aahText[13][0] = TEXT_CreateEx(30, 410, 120, 25,hWindow,WM_CF_SHOW,0,13,"控制导引:");

        for(x = 0;x < STATUE_LINE;x++)
        {
            TEXT_SetFont(_aahText[x][0], &XBF24_Font);
            TEXT_SetTextColor(_aahText[x][0], GUI_BLACK);
        }

        //创建编辑区
        _aahEdit[0][0] = EDIT_CreateEx(150, 20, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[1][0] = EDIT_CreateEx(150, 50, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[2][0] = EDIT_CreateEx(150,80, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[3][0] = EDIT_CreateEx(174, 110, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[4][0] = EDIT_CreateEx(174, 140, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[5][0] = EDIT_CreateEx(198, 170, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[6][0] = EDIT_CreateEx(198, 200, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[7][0] = EDIT_CreateEx(150,230, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[8][0] = EDIT_CreateEx(150,260, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[9][0] = EDIT_CreateEx(150, 290, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[10][0] = EDIT_CreateEx(150,320, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[11][0] = EDIT_CreateEx(174,350, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[12][0] = EDIT_CreateEx(174, 380, 96, 25,hWindow,WM_CF_SHOW,0,13,5);
        _aahEdit[13][0] = EDIT_CreateEx(150,410, 96, 25,hWindow,WM_CF_SHOW,0,13,5);

        for (y = 0; y < EDIT_MAX_Y; y++)
        {
            for (x = 0; x < EDIT_MAX_X; x++)
            {
                EDIT_SetText(_aahEdit[y][x],"无效");
                EDIT_SetTextAlign(_aahEdit[y][x], GUI_TA_HCENTER | GUI_TA_VCENTER);
                EDIT_SetFont(_aahEdit[y][x], &XBF24_Font);
            }
        }




//        TEXT_SetFont(pMsg->hWin, &XBF12_Font);
//        TEXT_SetTextColor(pMsg->hWin, GUI_BLACK);
//        _aahText[1][0] = TEXT_CreateEx(0, 40, 48, 22,hWindow,WM_CF_SHOW,0,13,"急停状态:");
//
//        TEXT_SetFont(pMsg->hWin, &XBF12_Font);
//        TEXT_SetTextColor(pMsg->hWin, GUI_BLACK);
//        _aahText[2][0] = TEXT_CreateEx(0, 80, 48, 22,hWindow,WM_CF_SHOW,0,13,"环境温度:");
//
//        TEXT_SetFont(pMsg->hWin, &XBF12_Font);
//        TEXT_SetTextColor(pMsg->hWin, GUI_BLACK);
//        _aahText[3][0] = TEXT_CreateEx(0, 120, 48, 22,hWindow,WM_CF_SHOW,0,13,"A插座温度:");
//
//        TEXT_SetFont(pMsg->hWin, &XBF12_Font);
//        TEXT_SetTextColor(pMsg->hWin, GUI_BLACK);
//        _aahText[4][0] = TEXT_CreateEx(0, 160, 48, 22,hWindow,WM_CF_SHOW,0,13,"B插座温度:");


        //创建编辑区
//        _aahEdit[0][0] = EDIT_CreateEx(0, 0, 48, 22,hWindow,WM_CF_SHOW,0,13,5);
//        _aahEdit[0][1] = EDIT_CreateEx(0,22, 48, 22,hWindow,WM_CF_SHOW,0,13,5);
//        _aahEdit[0][2] = EDIT_CreateEx(480,220, 48, 22,hWindow,WM_CF_SHOW,0,13,5);
//          for (y = 0; y < EDIT_MAX_Y; y++) {
//            for (x = 0; x < EDIT_MAX_X; x++) {
//              EDIT_SetTextAlign(_aahEdit[y][x], GUI_TA_RIGHT | GUI_TA_VCENTER);
//              EDIT_SetFont(_aahEdit[y][x], &GUI_Font8x16);
//              EDIT_SetDecMode(_aahEdit[y][x], ((y * EDIT_MAX_X) + x) * 100, -99999, +99999, 2, 0);
//            }
//          }
  /* Create the edit-fields */
  /* 创建编辑区域 */
//  for (y = 0; y < EDIT_MAX_Y; y++) {
//    for (x = 0; x < EDIT_MAX_X; x++) {
//		/* 创建编辑框 */
//      _aahEdit[y][x] = EDIT_CreateAsChild(x * 48, y * 22, 48, 22,
//                                        hWindow, 13, WM_CF_SHOW, 5);
//
//      /* 设置对齐方式和字体 */
//      EDIT_SetTextAlign(_aahEdit[y][x], GUI_TA_RIGHT | GUI_TA_VCENTER);
//      EDIT_SetFont(_aahEdit[y][x], &GUI_Font8x16);
//
//	  /* 句柄 要修改的数值 最大最小值，如果大于0，指定小数点的位置，标志位*/
//	  /* 启用编辑区的十进制编辑模式 给出的数值可以在给定的范围内显示 */
//      EDIT_SetDecMode(_aahEdit[y][x], ((y * EDIT_MAX_X) + x) * 100, -99999, +99999, 2, 0);
//	  }
//  }


        //
        //Initialization of 'Text'
        //
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_5),&XBF24_Font,GUI_BLACK,"交流电压:");
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6),&XBF24_Font,GUI_BLACK,"交流电流:");
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_7),&XBF24_Font,GUI_BLACK,"充电导引电压:");
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_8),&XBF24_Font,GUI_BLACK,"频    率:");
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_9),&XBF24_Font,GUI_BLACK,"A插座温度:");
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_10),&XBF24_Font,GUI_BLACK,"B插座温度:");
//        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_11),&XBF24_Font,GUI_BLACK,"接线温度:");
        //
        // Initialization of 'Edit'
        //
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0),&XBF24_Font,"00");
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),&XBF24_Font,"00");
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_2),&XBF24_Font,"00");
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_3),&XBF24_Font,"00");
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_4),&XBF24_Font,"00");
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_5),&XBF24_Font,"00");
//        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_6),&XBF24_Font,"00");
        //
        // Initialization of 'Button'
        //
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_GREEN,BUTTON_CI_UNPRESSED,GUI_RED,"信息查询");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_BLUE,BUTTON_CI_UNPRESSED,GUI_BLUE,"历史查询");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_BLUE,BUTTON_CI_UNPRESSED,GUI_BLUE,"系统配置");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_BLUE,BUTTON_CI_UNPRESSED,GUI_BLUE,"退    出");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF24_Font,BUTTON_CI_UNPRESSED,GUI_BLUE,BUTTON_CI_UNPRESSED,GUI_BLUE,"模拟量");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF24_Font,BUTTON_CI_UNPRESSED,GUI_BLUE,BUTTON_CI_UNPRESSED,GUI_RED,"状态量");
//        BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_GREEN);
//        BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),BUTTON_CI_UNPRESSED,GUI_GREEN);

//         BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), BUTTON_CI_DISABLED, GUI_GREEN);
//        BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), BUTTON_CI_PRESSED, GUI_GREEN);
//        BUTTON_SetBkColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2), BUTTON_CI_UNPRESSED, GUI_GREEN);


        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;

        switch(Id) {
        case ID_BUTTON_0: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_1: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_2: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_3: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_4: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_5: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
        }
        break;
        // USER START (Optionally insert additional message handling)
    case WM_TIMER:
        /* 显示时间和日期 */
        Timer_Process(pMsg);
        /* 重启定时器 */
        WM_RestartTimer(pMsg->Data.v, REFLASH);
        break;
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;

    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
// USER START (Optionally insert additional public code)
/*********************************************************************
*
*       CreateManagerInfoStatus
*/
WM_HWIN CreateManagerInfoStatus(void);
WM_HWIN CreateManagerInfoStatus(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    WM_CreateTimer(WM_GetClientWindow(hWin), ID_TimerTime, 1000, 0);

    return hWin;
}
/** @brief
 *  输出管理员界面里的信息查询状态量部分
 * @param
 * @param
 * @return
 *
 */

void PutOut_Manager_InfoStatus()
{
    CreateManagerInfoStatus();
    while(1)
    {
        dispbmp("system/dpc.bmp", 0, 5, 5, 1, 1);
        GUI_Delay(1000);
    }
//    dispbmp("system/dpc.bmp", 0, 5, 5, 1, 1);
//    GUI_Delay(1000);
}
// USER END

/*************************** End of file ****************************/



