
/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "xbffontcreate.h"
#include "touchtimer.h"
// USER END

#include "DIALOG.h"

#include "includes.h"
#include "dbparser.h"
#include "debug.h"

#include "order.h"
#include "interface.h"
#include "utils.h"

#define BYTES_LEN 1024

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
// USER START (Optionally insert additional defines)
#define ID_IMAGE_0    (GUI_ID_USER + 0x1C)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)

#define ID_BUTTON_0  (GUI_ID_USER + 0x00)//信息
#define ID_BUTTON_1  (GUI_ID_USER + 0x01)//历史
#define ID_BUTTON_2  (GUI_ID_USER + 0x02)//系统
#define ID_BUTTON_3  (GUI_ID_USER + 0x03)//退出
#define ID_BUTTON_4  (GUI_ID_USER + 0x04)//模拟
#define ID_BUTTON_5  (GUI_ID_USER + 0x05)//状态
#define ID_TEXT_5  (GUI_ID_USER + 0x06)//
#define ID_EDIT_0  (GUI_ID_USER + 0x07)//
#define ID_TEXT_6  (GUI_ID_USER + 0x08)//

#define ID_LISTWHEEL_0  (GUI_ID_USER + 0x10)
#define ID_LISTWHEEL_1  (GUI_ID_USER + 0x11)
#define ID_LISTWHEEL_2  (GUI_ID_USER + 0x12)
#define ID_LISTWHEEL_3  (GUI_ID_USER + 0x13)
#define ID_LISTWHEEL_4  (GUI_ID_USER + 0x14)
#define ID_LISTWHEEL_5  (GUI_ID_USER + 0x15)
#define ID_MULTIEDIT_0  (GUI_ID_USER + 0x16)
#define ID_LISTVIEW_0   (GUI_ID_USER + 0x17)

#define ID_TimerTime    1
#define ID_TimerFlush   2
#define ID_TimerSignal  3

#define ALARM_COLUMNS   4
#define CHARGE_COLUMNS  20
#define DB_DEBUG    1
//6 12 10
//1 2 1 2 1 2
//static uint8_t _alarmLog[] = {
//    "序号      开始时间            结束时间          告警内容\n\
// 01  2017-06-07 12:13:34  2017-06-08 12:13:23  急停故障"
//};
// USER END
static WM_HWIN _hWinManagerAlarmLog;
static WM_HTIMER _timerRTC,_timerData,_timerSignal;
uint16_t column_num,row_num;
/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
static const char *_apYear[]=
{
    "2004", "2005", "2006", "2007", "2008", "2009", "2010",
    "2011", "2012", "2013", "2014", "2015", "2016", "2017",
    "2018", "2019", "2020", "2021", "2022", "2023", "2024",
    "2025", "2026", "2027", "2028", "2029", "2030", "2031",
};
static const char *_apMonth[]=
{
    "01","02","03","04","05","06",
    "07","08","09","10","11","12",
};
static const char *_apDay[]=
{
    "01", "02", "03", "04", "05", "06",
    "07", "08", "09", "10", "11", "12",
    "13", "14", "15", "16", "17", "18",
    "19", "20", "21", "22", "23", "24",
    "25", "26", "27", "28", "29", "30", "31",
};

static DateStruct sel_start_date = {"2004","01","01"};
static DateStruct sel_end_date = {"2004","01","01"};
static uint8_t list_start_index[3];
static uint8_t list_end_index[3];

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
    { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 789, 459, 0, 0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 630, 0, 80, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 720, 0, 70, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 440, 0, 180, 16, 0, 0x0, 0 },//网络信号强度
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 225, 367, 300, 20, 0, 0x0, 0 },//最底端的说明
    { BUTTON_CreateIndirect, "信息查询", ID_BUTTON_0, 50, 70, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "历史记录", ID_BUTTON_1, 50, 140, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "系统配置", ID_BUTTON_2, 50, 210, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "退    出", ID_BUTTON_3, 50, 280, 150, 50, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "模拟量", ID_BUTTON_4, 550, 20, 80, 30, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "状态量", ID_BUTTON_5, 550, 52, 80, 30, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_0, 290, 25, 43, 50, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_1, 340, 25, 20, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Date", ID_TEXT_5, 243, 40, 50, 31, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_2, 365, 25, 20, 50, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_3, 450, 25, 43, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "TO", ID_TEXT_6, 400, 40, 50, 20, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_4, 500, 25, 20, 50, 0, 0x0, 0 },
    { LISTWHEEL_CreateIndirect, "Listwheel", ID_LISTWHEEL_5, 525, 25, 20, 50, 0, 0x0, 0 },
//    { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 210, 82, 560, 276, 0, 0x0, 0 },
    { LISTVIEW_CreateIndirect, "Listview", ID_LISTVIEW_0, 210, 82, 560, 276, 0, 0x0, 0 },//560,276
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
static void Data_Flush(WM_MESSAGE *pMsg)
{
}
/** @brief
 *
 * @param
 * @param
 * @return
 *
 */
static void DBselect_Data(uint8_t log_type,WM_HWIN hItem)
{
    char memseg[BYTES_LEN];
    char sel_cmd[100];
    char _tmpBuff[100];
    char sel_buf[20];
    char tbuf_start[80];
    db_query_mm_t mm;
    db_op_base_t* root;
    db_tuple_t    tuple;
    int i;
    char sn[32];
    char *p;
    int id;
    int balance;
    time_t _time;
    struct tm* _ptime;
    time_t  _psec;

#if DB_DEBUG
    p = sn;
    printf_safe("FILE REMOVE!!\n");
    db_fileremove("OrderLDBTest");
    vTaskDelay(10);
    init_query_mm(&mm, memseg, BYTES_LEN);
    printf_safe("CREATE TABLE!!\n");
    parse("CREATE TABLE OrderLDBTest (OrderSN       STRING(32), \
                                  CardID        STRING(32), \
                                  Balance       INT, \
                                  CONID         INT, \
                                  StartTime     INT, \
                                  StartType     INT, \
                                  LimitFee      INT, \
                                  StartPower    INT, \
                                  ServType      INT, \
                                  TotalPower    INT, \
                                  TotalPowerFee INT, \
                                  TotalServFee  INT, \
                                  TotalFee      INT, \
                                  TotalSeg      INT, \
                                  DefSegPower   INT, \
                                  DefSegFee     INT, \
                                  PayType       INT, \
                                  StopType      INT, \
                                  StopTime      STRING(32));", &mm);


    init_query_mm(&mm, memseg, BYTES_LEN);
    printf_safe("INSERT INTO OrderLDBTest!!\n");
    for(i = 0;i < 500;i++)
    {
        init_query_mm(&mm, memseg, BYTES_LEN);
        parse("INSERT INTO OrderLDBTest VALUES ('SN123123', 'id12323',12,1,1499695984,1,2,3,4,5,6,7,8,9,1,2,3,4,'2018');", &mm); //设置全部值
    }
    parse("INSERT INTO OrderLDBTest VALUES ('SN123123', 'id12323',12,1,1499695984,1,2,3,4,5,6,7,8,9,1,2,3,4,'2018');", &mm); //设置全部值
    parse("INSERT INTO OrderLDBTest VALUES ('SN123124', 'id12323',12,1,965267964,1,2,3,4,5,6,7,8,9,1,2,3,4,'2004');", &mm); //设置全部值
    parse("INSERT INTO OrderLDBTest VALUES ('SN123125', 'id12323',12,1,1579695984,1,2,3,4,5,6,7,8,9,1,2,3,4,'2005');", &mm); //设置全部值

    init_query_mm(&mm, memseg, BYTES_LEN);
    printf_safe("SELECT * FROM OrderLDBTest!!\n");
    root = parse("SELECT * FROM OrderLDBTest;", &mm);
    if (root == NULL)
    {
        printf_safe("NULL root\n");
    }
    else
    {
        init_tuple(&tuple, root->header->tuple_size, root->header->num_attr, &mm);

        while (next(root, &tuple, &mm) == 1)
        {
            id = getintbyname(&tuple, "CONID", root->header);
            balance = getintbyname(&tuple, "Balance", root->header);
            p = getstringbyname(&tuple, "OrderSN", root->header);
            printf_safe("balance: %d (%d)\n", balance, id);
            printf_safe("SN %s\n", p);
            _time = getintbyname(&tuple, "StartTime", root->header);
            //strftime (tbuf_start, sizeof (tbuf_start), "%Y-%m-%d %H:%M:%S", _time);
            printf_safe("startTime %d\n",_time);
            _time = getintbyname(&tuple, "StopTime", root->header);
            printf_safe("stopTime %d\n",_time);
        }
    }
    close_tuple(&tuple, &mm);
    closeexecutiontree(root, &mm);
#endif
    switch(log_type)
    {
        case 0:
            //故障log
        break;
        case 1:
            //充电log
            memset(sel_cmd,'\0',strlen(sel_cmd));
            memset(sel_buf,'\0',strlen(sel_buf));
            init_query_mm(&mm, memseg, BYTES_LEN);
            printf_safe("========================test select========================\n");
            strcpy(sel_cmd,"SELECT * FROM OrderLDBTest WHERE StartTime >= ");
            //关于日期的拼接
//            strcat(sel_buf,sel_start_date.year);
//            sprintf(sel_buf,"%s-%s-%s 00:00:00",sel_start_date.year,sel_start_date.month,sel_start_date.day);
//            strcat(sel_cmd,sel_buf);

//            strcat(sel_cmd," AND stopTime >= ");
//
//            memset(sel_buf,'\0',strlen(sel_buf));
//            sprintf(sel_buf,"%s-%s-%s 00:00:00",sel_end_date.year,sel_end_date.month,sel_end_date.day);
//            strcat(sel_cmd,sel_buf);
            /**<  上述为拼接以标准日期形式的时间;下述改为拼接秒的形式 */
            /**<  下述两句进行_ptime的类似初始化,不进行此操作下述赋值会死机,未接之谜 */
            _time = time(NULL);
            _ptime = localtime(&_time);
//            _psec = mktime(_ptime);
//            sprintf(sel_buf,"%d;",_psec);

            _ptime->tm_year = atoi(sel_start_date.year) - 1900;
            _ptime->tm_mon = atoi(sel_start_date.month) - 1;
            _ptime->tm_mday = atoi(sel_start_date.day);
            _ptime->tm_hour = 0;
            _ptime->tm_min = 0;
            _ptime->tm_sec = 0;
            _ptime->tm_wday = (atoi(sel_start_date.year)-2000 + 2 * (atoi(sel_start_date.month)) + 3 * (atoi(sel_start_date.month) + 1) / 5 + atoi(sel_start_date.day) + atoi(sel_start_date.day) / 4 - atoi(sel_start_date.day) / 100 + atoi(sel_start_date.day) / 400) % 7;
            _ptime->tm_yday = 0;
            _ptime->tm_isdst = 0;

//            printf_safe("\ntm_year = %d,tm_mon = %d,tm_mday = %d\n  \
//                        tm_hour = %d,tm_min = %d,tm_sec = %d\n  \
//                        tm_wday = %d,tm_yday = %d,tm_isdst = %d\n   \
//                            ",_ptime->tm_year,_ptime->tm_mon,_ptime->tm_mday,   \
//                            _ptime->tm_hour,_ptime->tm_min,_ptime->tm_hour,     \
//                            _ptime->tm_wday,_ptime->tm_yday,_ptime->tm_isdst);

            _psec = mktime(_ptime);

            sprintf(sel_buf,"%d;",_psec);
            strcat(sel_cmd,sel_buf);

//            printf_safe("\n%s\n",sel_cmd);
            //printf_safe("SELECT * FROM OrderLDBTest WHERE startTime > 0 AND stopTime > 0\n");
            //root = parse("SELECT * FROM OrderLDBTest WHERE StartTime > 2004;",&mm);
            //root = parse("SELECT * FROM OrderLDBTest WHERE StartTime >= 1072886400;", &mm);

            root = parse(sel_cmd,&mm);
            if (root == NULL)
            {
                printf_safe("NULL root\n");
            }
            else
            {
                init_tuple(&tuple, root->header->tuple_size, root->header->num_attr, &mm);
                i = 0;
                while (next(root, &tuple, &mm) == 1)
                {
                    LISTVIEW_AddRow(hItem, NULL);
                    xsprintf((char *)_tmpBuff, "%03d", (i+1));
                    LISTVIEW_SetItemText(hItem, 0, i, _tmpBuff);
                    p = getstringbyname(&tuple, "OrderSN", root->header);
                    LISTVIEW_SetItemText(hItem, 1, i, p);
                    p = getstringbyname(&tuple, "CardID", root->header);
                    LISTVIEW_SetItemText(hItem, 2, i, p);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "Balance", root->header));
                    LISTVIEW_SetItemText(hItem, 3, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "CONID", root->header));
                    LISTVIEW_SetItemText(hItem, 4, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "StartTime", root->header));
                    LISTVIEW_SetItemText(hItem, 5, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "StartType", root->header));
                    LISTVIEW_SetItemText(hItem, 6, i, _tmpBuff);

                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "LimitFee", root->header));
                    LISTVIEW_SetItemText(hItem, 7, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "StartPower", root->header));
                    LISTVIEW_SetItemText(hItem, 8, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "ServType", root->header));
                    LISTVIEW_SetItemText(hItem, 9, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "TotalPower", root->header));
                    LISTVIEW_SetItemText(hItem, 10, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "TotalPowerFee", root->header));
                    LISTVIEW_SetItemText(hItem, 11, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "TotalServFee", root->header));
                    LISTVIEW_SetItemText(hItem, 12, i, _tmpBuff);

                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "TotalFee", root->header));
                    LISTVIEW_SetItemText(hItem, 13, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "TotalSeg", root->header));
                    LISTVIEW_SetItemText(hItem, 14, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "DefSegPower", root->header));
                    LISTVIEW_SetItemText(hItem, 15, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "DefSegFee", root->header));
                    LISTVIEW_SetItemText(hItem, 16, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "PayType", root->header));
                    LISTVIEW_SetItemText(hItem, 17, i, _tmpBuff);
                    xsprintf((char *)_tmpBuff, "%d", getintbyname(&tuple, "StopType", root->header));
                    LISTVIEW_SetItemText(hItem, 18, i, _tmpBuff);
                    LISTVIEW_SetItemText(hItem, 19, i, getstringbyname(&tuple, "StopTime", root->header));
                    i++;
                }
            }
            printf_safe("\n查找到的充电记录条数: %d 条\n",i);
            close_tuple(&tuple, &mm);
            closeexecutiontree(root, &mm);
        break;
    }
}

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    volatile WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;
    uint16_t     i,_strNum[3];
	volatile HEADER_Handle hHeader;
	char    buf[20];
//	static char  Value = 0;
    SCROLLBAR_Handle hScroll;
    SCROLLBAR_Handle wScroll;
//    static int _x,_y;
//    WM_SCROLL_STATE ScrollState;

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        WM_SetFocus(_hWinManagerAlarmLog);
        /// TODO (zshare#1#): 下面的if不起作用.\
        但是if里嵌套的if起作用,目前先用此来规避不起作用的if
        if(_hWinManagerAlarmLog == cur_win)
        {
            /**< 数据处理 */
            //Data_Process(pMsg);
            /**< 信号数据处理 */
            Signal_Show();
            /**< 灯光控制 */
            Led_Show();
            /**< 如果界面发生了切换 */
            if(_hWinManagerAlarmLog == cur_win)
            {
                /**< 故障分析 */
                //Err_Analy(pMsg->hWin);
                /**< 特殊触控点分析 */
                CaliDone_Analy(pMsg->hWin);
            }
        }
        break;
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        FrameWin_Init(pMsg, ID_TEXT_1, ID_TEXT_2, ID_TEXT_3, ID_TEXT_4,ID_IMAGE_0);
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_5),&XBF16_Font,GUI_BLACK,"起始");
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6),&XBF16_Font,GUI_BLACK,"终止");
        //
        // Initialization of 'Button'
        //
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_GREEN,BUTTON_CI_UNPRESSED,GUI_BLACK,"信息查询");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_RED,BUTTON_CI_UNPRESSED,GUI_RED,"历史查询");
        BUTTON_SetPressed(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),1);
        BUTTON_SetTextColor(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1),BUTTON_CI_PRESSED,GUI_RED);

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"系统配置");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF36_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"退    出");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF19_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"查询告警");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5),GUI_TA_HCENTER|GUI_TA_VCENTER,
                    &XBF19_Font,BUTTON_CI_UNPRESSED,GUI_BLACK,BUTTON_CI_UNPRESSED,GUI_BLACK,"查询充电");
        //
        // Initialization of 'Listwheel'
        //
        //初始化listwheel
        for(i = 0;i < 6;i++)
        {
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0+i);
            //设置字体
            LISTWHEEL_SetFont(hItem,&GUI_FontComic18B_ASCII);
            LISTWHEEL_SetTextAlign(hItem,GUI_TA_VCENTER | GUI_TA_VERTICAL);
            //设置吸附位置
            LISTWHEEL_SetSnapPosition(hItem,15);
            //设置绘制数据项所使用的行高
        //        LISTWHEEL_SetLineHeight(hItem,30);
            //设置选中的条目的文本颜色
            LISTWHEEL_SetTextColor(hItem,LISTWHEEL_CI_SEL,GUI_RED);
        }
        //设置起始年listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
        //绘制指示行
        //    LISTWHEEL_SetOwnerDraw(hItem,ListWheel0_OwnerDraw);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apYear);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apYear+i));
        }

        //设置起始月listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apMonth);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apMonth+i));
        }

        //设置起始日listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apDay);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apDay+i));
        }

        //设置终止年listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apYear);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apYear+i));
        }

        //设置终止月listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apMonth);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apMonth+i));
        }

        //设置终止日listwheel
        hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
        //添加数据
        for(i = 0;i < GUI_COUNTOF(_apDay);i++)
        {
            LISTWHEEL_AddString(hItem,*(_apDay+i));
        }
//        //初始化multiedit
//        hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
//        MULTIEDIT_SetAutoScrollH(hItem,1);
//        MULTIEDIT_SetAutoScrollV(hItem,1);
//        MULTIEDIT_SetInsertMode(hItem, 1);
//        MULTIEDIT_SetFont(hItem, &XBF24_Font);
//        MULTIEDIT_SetCursorOffset(hItem,0);
//        MULTIEDIT_EnableBlink(hItem,0,0);
//        //memset(_alarmLog,'\0',strlen(_alarmLog));
//        MULTIEDIT_SetText(hItem, " ");
////        SCROLLBAR_CreateAttached(hItem, SCROLLBAR_CF_VERTICAL);//创建垂直滑轮
////        SCROLLBAR_CreateAttached(hItem, 0);//创建水平滑轮
			//
			// 初始列表控件
			//
			hItem = WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0);
			/* 设置列表控件中header控件的所显示文本的字体 */
			hHeader = LISTVIEW_GetHeader(hItem);
			HEADER_SetFont(hHeader, &XBF16_Font);
//            LISTVIEW_SetAutoScrollH(hItem,1);
//            LISTVIEW_SetAutoScrollV(hItem,1);

            /*srollbar*/
            hScroll = SCROLLBAR_CreateAttached(hItem, 0);//水平滑轮
            SCROLLBAR_SetNumItems(hScroll, 30 * 4);
            SCROLLBAR_SetWidth(hScroll,20);
            wScroll = SCROLLBAR_CreateAttached(hItem, SCROLLBAR_CF_VERTICAL);//垂直滑轮
            SCROLLBAR_SetNumItems(wScroll, 30 * 20);
            SCROLLBAR_SetWidth(wScroll,20);
            /*end*/

            //SCROLLBAR_SetDefaultWidth(15);
			/* 设置列表控件选项中所显示文本的字体 */
			LISTVIEW_SetFont(hItem, &XBF16_Font);
			/* 设置列表控件表格可见 */
			LISTVIEW_SetGridVis(hItem, 1);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id) {
            /*scrollbar*/
//        case GUI_ID_HSCROLL:
//            if(NCode == WM_NOTIFICATION_VALUE_CHANGED)
//            {
//                   /* 得到滚动条的状态，得到的数值好像是负值 才能使得 _x - ScrollState.v是正值 */
//                    WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
//                    if (_x != ScrollState.v)
//                    {
//                        WM_MoveWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), _x - ScrollState.v, 0);
//                        _x = ScrollState.v;
//                    }
//            }
//            else if(NCode == GUI_ID_VSCROLL)
//            {
//                    WM_GetScrollState(pMsg->hWinSrc, &ScrollState);
//                    if (_y != ScrollState.v)
//                    {
//                        WM_MoveWindow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),0, _y - ScrollState.v);
//                        _y = ScrollState.v;
//                    }
//            }
//            break;
            /*end*/
        case ID_BUTTON_0: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            /**< 跳转到模拟量信息查询 */
            _deleteWin(_hWinManagerAlarmLog);
            CreateManagerInfoAnalog();
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_1: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_2: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            /**< 跳转到模拟量信息查询 */
            _deleteWin(_hWinManagerAlarmLog);
            CreateManagerSysSet();
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_3: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            //WM_DeleteWindow(pMsg->hWin);
            //PutOut_SelAOrB();
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_4: //查询故障 Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            /**< get到现有表格的行列数 */
            column_num = LISTVIEW_GetNumColumns(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
            for(i = 0;i < column_num;i++)
            {
                LISTVIEW_DeleteColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),0);
            }

			/* 添加四列表，调用一次函数LISTVIEW_AddColumn添加一列 */
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "序号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "起始时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "结束时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "告警内容", GUI_TA_HCENTER | GUI_TA_VCENTER);

			/* 添加三行，调用一次函数LISTVIEW_AddRow添加一行 */
//			LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);
//			LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);
//			LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);


            DBselect_Data(0,WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));

//            for(i = 0; i< 500;i++)
//            {
//                LISTVIEW_AddRow(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), NULL);
//                sprintf(buf, "%03d", i+1);
//                //序号
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, i, buf);
////                memset(buf,'\0',strlen(buf));
//                strcpy(buf, "2016-07-07 12:13:14");
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, i, buf);
////                memset(buf,'\0',strlen(buf));
//                strcpy(buf, "2016-07-07 12:13:14");
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, i, buf);
////                memset(buf,'\0',strlen(buf));
//                strcpy(buf, "i");
//                LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, i, buf);
//            }

			/* 为列表控件三行四列共12个选项全部添加文本 */
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 0, "00");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, 0, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, 0, "2016-07-07 12:14:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, 0, "急停故障");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 1, "01");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, 1, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, 1, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, 1, "交流过压");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 0, 2, "02");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 1, 2, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 2, 2, "2016-07-07 12:13:14");
//			LISTVIEW_SetItemText(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 3, 2, "继电器故障");
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_BUTTON_5: // Notifications sent by 'Button'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            column_num = LISTVIEW_GetNumColumns(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));
            for(i = 0;i < column_num;i++)
            {
                LISTVIEW_DeleteColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0),0);
            }

			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 80, "序号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "订单号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "卡号", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "余额", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "枪ID", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "起始时间", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "起始类型", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "限制余额", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "起始电量", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "服务类型", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "充电电量", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "充电电费", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "充电服务费", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "总费用", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "时间段电量", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "时间段电费", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "支付方式", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "停止类型", GUI_TA_HCENTER | GUI_TA_VCENTER);
			LISTVIEW_AddColumn(WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0), 160, "结束时间", GUI_TA_HCENTER | GUI_TA_VCENTER);

            DBselect_Data(1,WM_GetDialogItem(pMsg->hWin, ID_LISTVIEW_0));

            break;
        /// TODO (zshare#1#): ///因为鼠标重置的问题, \
        所以需要用到WM_NOTIFICATION_MOVED_OUT事件,不触发WM_NOTIFICATION_RELEASED
          case WM_NOTIFICATION_RELEASED://WM_NOTIFICATION_MOVED_OUT:
            /**< 跳转到状态信息查询 */
//            _deleteWin(_hWinManagerInfoAnalog);
//            CreateManagerInfoStatus();
            break;
          }
            break;
        case ID_LISTWHEEL_0: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            //获取句柄
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_0);
            //获取当前句柄索引
            list_start_index[0] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_start_index[0]);
            LISTWHEEL_GetItemText(hItem,list_start_index[0],sel_start_date.year,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_1: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            //获取句柄
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_1);
            //获取当前句柄索引
            list_start_index[1] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_start_index[1]);
            LISTWHEEL_GetItemText(hItem,list_start_index[1],sel_start_date.month,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_2: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            //获取句柄
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_2);
            //获取当前句柄索引
            list_start_index[2] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_start_index[2]);
            LISTWHEEL_GetItemText(hItem,list_start_index[2],sel_start_date.day,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_3: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_3);
            //获取当前句柄索引
            list_end_index[0] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_end_index[0]);
            LISTWHEEL_GetItemText(hItem,list_end_index[0],sel_end_date.year,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_4: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_4);
            //获取当前句柄索引
            list_end_index[1] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_end_index[1]);
            LISTWHEEL_GetItemText(hItem,list_end_index[1],sel_end_date.month,5);
            // USER END
            break;
          // USER START (Optionally insert additional code for further notification handling)
          // USER END
          }
          break;
        case ID_LISTWHEEL_5: // Notifications sent by 'Listwheel'
          switch(NCode) {
          case WM_NOTIFICATION_CLICKED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_RELEASED:
            // USER START (Optionally insert code for reacting on notification message)
            // USER END
            break;
          case WM_NOTIFICATION_SEL_CHANGED:
            // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin,ID_LISTWHEEL_5);
            //获取当前句柄索引
            list_end_index[2] = LISTWHEEL_GetPos(hItem);
            //设置当前句柄数据项
            LISTWHEEL_SetSel(hItem,list_end_index[2]);
            LISTWHEEL_GetItemText(hItem,list_end_index[2],sel_end_date.day,5);
            // USER END
            break;
        }
        break;
    }
    case WM_TIMER:
        if(pMsg->Data.v == _timerRTC)
        {
            /**< 显示时间和日期 */
            Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);
            TEXT_SetText(WM_GetDialogItem(pMsg->hWin, ID_TEXT_3), strCSQ);
            /**< 重启定时器 */
            WM_RestartTimer(pMsg->Data.v, 20);
        }
        if(pMsg->Data.v == _timerSignal)
        {
            WM_RestartTimer(pMsg->Data.v, 2000);
        }
        if(pMsg->Data.v == _timerData)
        {
            //Data_Flush(pMsg);
            WM_RestartTimer(pMsg->Data.v,5000);
        }
        break;
    case MSG_CREATERRWIN:
        /**< 故障界面不存在则创建,存在则刷新告警 */
        err_window(pMsg->hWin);
        break;
    case MSG_DELERRWIN:
        /**< 故障界面存在则删除故障界面 */
        if(bittest(winCreateFlag,0))
        {
            bitclr(winCreateFlag,0);
            GUI_EndDialog(err_hItem,0);
            err_hItem = 0;
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
/** @brief
 *  输出管理员界面里的信息查询告警记录部分
 * @param
 * @param
 * @return
 *       CreateManagerAlarmLog
*/
WM_HWIN CreateManagerAlarmLog(void);
WM_HWIN CreateManagerAlarmLog(void)
{
    _hWinManagerAlarmLog = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    cur_win = _hWinManagerAlarmLog;
    _timerRTC = WM_CreateTimer(WM_GetClientWindow(_hWinManagerAlarmLog), ID_TimerTime, 20, 0);
    _timerData = WM_CreateTimer(WM_GetClientWindow(_hWinManagerAlarmLog), ID_TimerFlush,1000,0);
    _timerSignal = WM_CreateTimer(WM_GetClientWindow(_hWinManagerAlarmLog), ID_TimerSignal,5000,0);
}
/*************************** End of file ****************************/



