/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "xbffontcreate.h"
#include "touchtimer.h"
#include "interface.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)
// USER START (Optionally insert additional defines)
#define ID_BUTTON_1   (GUI_ID_USER + 0x08)
#define ID_TEXT_0     (GUI_ID_USER + 0x0A)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)
#define ID_TEXT_5     (GUI_ID_USER + 0x05)
#define ID_TEXT_6     (GUI_ID_USER + 0x02)
#define ID_TEXT_7     (GUI_ID_USER + 0x03)
#define ID_TEXT_8     (GUI_ID_USER + 0x04)
#define ID_EDIT_0     (GUI_ID_USER + 0x06)
#define ID_EDIT_1     (GUI_ID_USER + 0x07)
#define ID_TimerTime    0
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCardInfo
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCardInfo[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
    // USER START (Optionally insert additional widgets)
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 630, 0, 80, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 720, 0, 70, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 540, 0, 90, 16, 0, 0x0, 0 },//网络信号强度
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 225, 367, 300, 20, 0, 0x0, 0 },//最底端的说明
    { BUTTON_CreateIndirect, "退出", ID_BUTTON_0, 554, 317, 100, 36, 0, 0x0, 0 },//倒计时退出
    { BUTTON_CreateIndirect, "确定", ID_BUTTON_1, 554, 272, 100, 36, 0, 0x0, 0 },//枪锁完全锁止后的确认按钮
    { TEXT_CreateIndirect, "Text", ID_TEXT_5, 600, 324, 61, 24, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_6, 223, 228, 500, 61, 0, 0x0, 0 },//是否提示余额不足
    { TEXT_CreateIndirect, "Text", ID_TEXT_0, 222, 149, 80, 30, 0, 0x0, 0 }, //卡号
    { TEXT_CreateIndirect, "Text", ID_TEXT_7, 222, 184, 80, 30, 0, 0x0, 0 }, //余额
    { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 313, 149, 255, 30, 0, 0x64, 0 },//卡号号码
    { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 313, 184, 93, 27, 0, 0x64, 0 },//余额钱
    { TEXT_CreateIndirect, "Text", ID_TEXT_8, 417, 184, 80, 30, 0, 0x0, 0 },//余额单位
    // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
static void Caculate_RTC(WM_MESSAGE *pMsg)
{
    uint8_t i = 1;
    static uint8_t num = 0;
    uint8_t Timer_buf[10];
    EventBits_t uxBitRFID;
    EventBits_t uxBitCharge;
    CON_t *pCON;

    WM_HWIN hWin = pMsg->hWin;

    pCON = CONGetHandle(0);
    uxBitCharge = xEventGroupGetBits(pCON->status.xHandleEventCharge);
    if((uxBitCharge & defEventBitCONStartOK) == defEventBitCONStartOK)
    {
        /** @todo (zshare#1#): 跳转充电界面 */
        PutOut_Charging();
    }
    else
    {
        /** @todo (zshare#1#): 充电条件未达成 */
    }
    Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);

    xsprintf((char *)Timer_buf, "(%02dS)", wait_timer.card_info);

    //if(ChargePointStateType.xPlugState == PLUG) // 枪已插好
    //xQueueReceive(xHandleQueueOrders,&order,10);//接收枪锁信息队列
    //解析队列信息
    //Point_Info[current_id_disp].point_statue =
////    if(Point_Info[current_id_disp].point_statue == STATE_POINT_IDLE)
////    {
////        TEXT_SetText(WM_GetDialogItem(hWin,ID_TEXT_6), "请连接充电枪头!");
////    }
////    else if(Point_Info[current_id_disp].point_statue == STATE_POINT_PRECONTRACT_LOSEPLUG)
////    {
////        BUTTON_SetBkColor(WM_GetDialogItem(hWin,ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_RED);
////        BUTTON_SetTextColor(WM_GetDialogItem(hWin,ID_BUTTON_1),BUTTON_CI_UNPRESSED,GUI_BLUE);
////        BUTTON_SetText(WM_GetDialogItem(hWin,ID_BUTTON_1),"确定");
////        TEXT_SetText(WM_GetDialogItem(hWin,ID_TEXT_6), "枪锁未锁止，是否继续充电?");
////    }
////    else if(Point_Info[current_id_disp].point_statue == STATE_POINT_CHARGING)
////    {
////        //正在充电
////        PutOut_Charging();
////    }

    if((num++) >= (1000 / REFLASH))
    {
        num = 0;
        if((wait_timer.card_info--) == 0)
        {
            wait_timer.card_info = 0;
            //未操作计时结束调转home页
            xEventGroupSetBits(xHandleEventHMI, defEventBitHMITimeOutToRFID);
            PutOut_Home();
        }
    }

    TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_5), Timer_buf);

    uxBitRFID = xEventGroupWaitBits(pRFIDDev->xHandleEventGroupRFID,
                                    defEventBitGoodIDReqDisp,
                                    pdTRUE, pdTRUE, 0);
    if((uxBitRFID & defEventBitGoodIDReqDisp) == defEventBitGoodIDReqDisp)
    {
        pCON = CONGetHandle(0);//选择枪的时候获取pCON

        sprintf(Timer_buf, "%.2lf", pRFIDDev->order.dBalance);


        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6), &XBF36_Font, GUI_RED, " ");
        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1), &XBF24_Font, Timer_buf);
        xEventGroupSetBits(pRFIDDev->xHandleEventGroupRFID, defEventBitGoodIDReqDispOK);

    }


    uxBitRFID = xEventGroupWaitBits(pRFIDDev->xHandleEventGroupRFID,
                                    defEventBitBadIDReqDisp,
                                    pdTRUE, pdTRUE, 0);
    if((uxBitRFID & defEventBitBadIDReqDisp) == defEventBitBadIDReqDisp)
    {
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6), &XBF36_Font, GUI_RED, "此卡未注册");
        /** @todo (zshare#1#): 未注册卡处理流程 ，处理完成之后，发送DispOK事件*/
        xEventGroupSetBits(pRFIDDev->xHandleEventGroupRFID, defEventBitBadIDReqDispOK);
    }
    uxBitRFID = xEventGroupWaitBits(pRFIDDev->xHandleEventGroupRFID,
                                    defEventBitOweIDReqDisp,
                                    pdTRUE, pdTRUE, 0);
    if((uxBitRFID & defEventBitOweIDReqDisp) == defEventBitOweIDReqDisp)
    {
        sprintf(Timer_buf, "%.2lf", pRFIDDev->order.dBalance);
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6), &XBF36_Font, GUI_RED, "此卡已欠费");
        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1), &XBF24_Font, Timer_buf);

        /** @todo (zshare#1#): 定10s退出 */
        xEventGroupSetBits(pRFIDDev->xHandleEventGroupRFID, defEventBitOwdIDReqDispOK);
    }
    pCON = CONGetHandle(0);//选择枪的时候获取pCON
    /*未进GoodID ,BadID和OweID状态时显示内容*/
    if(pCON->status.xPlugState == UNPLUG)
    {
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6), &XBF36_Font, GUI_RED, "请连接充电插头");
    }

    /*end of 未进GoodID ,BadID和OweID状态时显示内容*/
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;
    // USER START (Optionally insert additional variables)
    uint8_t temp_buf[32];
    int i;
    // USER END

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Framewin'
        //
        FrameWin_Init(pMsg, ID_TEXT_1, ID_TEXT_2, ID_TEXT_3, ID_TEXT_4);
        //
        // Initialization of 'Text'
        //
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_0), &XBF24_Font, GUI_BLACK, "卡号");
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_7), &XBF24_Font, GUI_BLACK, "余额");
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_8), &XBF24_Font, GUI_BLACK, "元");
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_5), &XBF24_Font, GUI_BLACK, "(60S)");
        //
        // Initialization of 'Edit'
        //

        HexToStr(pRFIDDev->order.ucCardID, temp_buf, defCardIDLength);
        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_0), &XBF24_Font, temp_buf);         //卡号
////        memset(temp_buf,'\0',sizeof(temp_buf));
////        xsprintf((char *)temp_buf, "(%02d)", Card_Info[current_id_disp].balance);
////        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1),&XBF24_Font,temp_buf);
        Edit_Show(WM_GetDialogItem(pMsg->hWin, ID_EDIT_1), &XBF24_Font, "?");

        //if(Card_Info[current_id_disp].balance <= 0)

//            Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6),&XBF36_Font,GUI_RED, "余额不足请充值");
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_6), &XBF36_Font, GUI_RED, "正在获取账户信息...");

        //
        // Initialization of 'Button'
        //
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), GUI_TA_LEFT | GUI_TA_VCENTER,
                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "    ");

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), GUI_TA_LEFT | GUI_TA_VCENTER,
                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "退出");
        // USER END
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_0: // Notifications sent by 'Button'
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                PutOut_Home();
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
        // USER START (Optionally insert additional message handling)
    case WM_TIMER:
        /* 显示时间和日期 */
        Caculate_RTC(pMsg);
        /* 重启定时器 */
        WM_RestartTimer(pMsg->Data.v, REFLASH);
        break;
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCardInfo
*/
WM_HWIN CreateCardInfo(void);
WM_HWIN CreateCardInfo(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCardInfo, GUI_COUNTOF(_aDialogCardInfo), _cbDialog, WM_HBKWIN, 0, 0);
    WM_CreateTimer(WM_GetClientWindow(hWin), ID_TimerTime, 1000, 0);

    return hWin;
}

// USER START (Optionally insert additional public code)

/** @brief
 *  输出卡片信息界面
 * @param
 * @param
 * @return
 *
 */
void PutOut_Card_Info()//(OrderData_t *order)
{
    uint8_t i = 0;
    wait_timer.card_info = 60;

//    for(i = 0;i < Sys_Info.charge_gun_num;i++)
//    {
//        if(Card_Info[i].charge_gun_status == 0)//可用
//        {
//            current_id_disp = i;
//            Card_Info[i].id = order.ucUID[0]<<24 + order.ucUID[0]<<16 + order.ucUID[0]<<8 + order.ucUID[0]<<24;
//            Card_Info[i].status = order.ucAccountStatus;
//            Card_Info[i].balance = order.dBalance;
//            order.ucPointID = i;
//            xQueueSend(xHandleQueueOrders,&order,10);
//            break;
//        }
//    }

    if(Sys_Info.charge_gun_num == i)
    {
        ;//不区分单双枪，枪都在使用中。
    }

    CreateCardInfo();
    while(1)
    {
        dispbmp("system/dpc.bmp", 0, 5, 5, 1, 1);
        GUI_Delay(500);
    }
}
// USER END

/*************************** End of file ****************************/



