/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "xbffontcreate.h"
#include "touchtimer.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_IMAGE_0      (GUI_ID_USER + 0x09)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)
#define ID_TEXT_0     (GUI_ID_USER + 0x08)
// USER START (Optionally insert additional defines)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)

#define ID_TimerTime    0

uint8_t *Regitster_Content = {"1,打开APP.\r\n2,选择注册."};
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
    { IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 0, 0, 789, 459, 0, 0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 700, 350, 60, 40, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_0, 245, 99, 254, 50, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 630, 0, 80, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 720, 0, 70, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 540, 0, 90, 16, 0, 0x0, 0 },//网络信号强度
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 225, 367, 300, 20, 0, 0x0, 0 },//最底端的说明
};
/*********************************************************************
*
*       Static code
*   数据处理函数
**********************************************************************
*/
static void Data_Process(WM_MESSAGE *pMsg)
{
    uint8_t strCSQ[10];
    EventBits_t uxBits;

    WM_HWIN hWin = pMsg->hWin;

    memset(strCSQ,'\0',strlen(strCSQ));
    sprintf(strCSQ, "信号:%.2d", pModem->status.ucSignalQuality);
    uxBits = xEventGroupGetBits(xHandleEventTCP);
    if((uxBits & defEventBitTCPConnectOK) != defEventBitTCPConnectOK)
    {
        strcat(strCSQ," 服务器未连接");
    }
    else
    {
        strcat(strCSQ," 服务器已连接");
    }

    TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), strCSQ);
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    WM_HWIN      hItem;
    WM_HWIN      hMulti;       //多行文本
    int          NCode;
    int          Id;

    switch (pMsg->MsgId)
    {
    case WM_PAINT:
        /**< 数据刷新 */
        Data_Process(pMsg);
        /**< 故障分析 */
        Err_Analy(pMsg->hWin);
        /**< 灯光控制 */
        Led_Show();
        /**< 特殊触控点分析 */
        CaliDone_Analy(pMsg->hWin);
        break;
    case WM_INIT_DIALOG:
        FrameWin_Init(pMsg, ID_TEXT_1, ID_TEXT_2, ID_TEXT_3, ID_TEXT_4,ID_IMAGE_0);

        hMulti = MULTIEDIT_CreateEx(100, 50, 580, 300, WM_GetClientWindow(pMsg->hWin), WM_CF_SHOW, 0, GUI_ID_MULTIEDIT0, 100, NULL);
        //MULTIEDIT_EnableBlink(hMulti,500,1);			//开启光标,周期500ms
        MULTIEDIT_SetInsertMode(hMulti,1);  //开启插入模式
        MULTIEDIT_SetFont(hMulti, &XBF24_Font);
//        MULTIEDIT_SetTextColor(hMulti,MULTIEDIT_CI_READONLY,GUI_RED);
        WM_SetFocus(hMulti);
        MULTIEDIT_SetText(hMulti,Regitster_Content);

        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), GUI_TA_LEFT | GUI_TA_VCENTER,
                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "退出");
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_0:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                /**< 跳转回home首页 */
                WM_DeleteWindow(pMsg->hWin);
                CreateHome();
                break;
            case WM_NOTIFICATION_RELEASED:

                break;
            }
            break;
        }
        break;
    case WM_TIMER:
        /**< 显示时间和日期 */
        Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);
        /**< 重启定时器 */
        WM_RestartTimer(pMsg->Data.v, 20);
        break;
    case MSG_CREATERRWIN:
        /**< 故障界面不存在则创建,存在则刷新告警 */
        err_window(pMsg->hWin);
        break;
    case MSG_DELERRWIN:
        /**< 故障界面存在则删除故障界面 */
        if(bittest(winCreateFlag,0))
        {
            bitclr(winCreateFlag,0);
            GUI_EndDialog(err_hItem,0);
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*** @brief
 *  卡片非法情况下显示注册流程
 * @param
 * @param
 * @return
 *
 *
 *  CreateRegiterDisp
*/
WM_HWIN CreateRegiterDisp(void);
WM_HWIN CreateRegiterDisp(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    WM_CreateTimer(WM_GetClientWindow(hWin), ID_TimerTime, 20, 0);

    return hWin;
}
/*************************** End of file ****************************/


