/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.30                          *
*        Compiled Jul  1 2015, 10:50:32                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "xbffontcreate.h"
#include "touchtimer.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0     (GUI_ID_USER + 0x00)
#define ID_BUTTON_0     (GUI_ID_USER + 0x01)
#define ID_BUTTON_1     (GUI_ID_USER + 0x04)
#define ID_TEXT_0     (GUI_ID_USER + 0x11)
#define ID_TEXT_1     (GUI_ID_USER + 0x0B)
#define ID_TEXT_2     (GUI_ID_USER + 0x0C)
#define ID_TEXT_3     (GUI_ID_USER + 0x0D)
#define ID_TEXT_4     (GUI_ID_USER + 0x0E)

#define ID_TimerTime    0

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { FRAMEWIN_CreateIndirect, "Framewin", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 67, 146, 250, 40, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 404, 146, 250, 40, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_0, 245, 50, 254, 50, 0, 0x0, 0 },

    { TEXT_CreateIndirect, "Text", ID_TEXT_1, 630, 0, 80, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_2, 720, 0, 70, 16, 0, 0x0, 0 },
    { TEXT_CreateIndirect, "Text", ID_TEXT_3, 540, 0, 90, 16, 0, 0x0, 0 },//网络信号强度
    { TEXT_CreateIndirect, "Text", ID_TEXT_4, 225, 367, 300, 20, 0, 0x0, 0 },//最底端的说明
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
// USER START (Optionally insert additional static code)
static void Timer_Process(WM_MESSAGE *pMsg)
{
    uint8_t i = 0;
    WM_HWIN hWin_Error;
    WM_HWIN hWin = pMsg->hWin;

    Jump_IsManager(hWin);
    Caculate_RTC_Show(pMsg, ID_TEXT_1, ID_TEXT_2);

    //需要增加3G模块的信号强度判断
    switch(i % 5)
    {
    case 0:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:非常强");
        break;
    case 1:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:一般");
        break;
    case 2:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:差");
        break;
    case 3:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:极差");
        break;
    default:
        TEXT_SetText(WM_GetDialogItem(hWin, ID_TEXT_3), "信号:无");
        break;
    }
    /// TODO (zshare#1#): //添加哪个枪在使用中。。。

//            Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), GUI_TA_LEFT | GUI_TA_VCENTER,
//                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "A枪");
//        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), GUI_TA_HCENTER | GUI_TA_VCENTER,
//                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "B枪");
//
//
}
/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE *pMsg)
{
    const void *pData;
    WM_HWIN      hItem;
    U32          FileSize;
    int          NCode;
    int          Id;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        FrameWin_Init(pMsg, ID_TEXT_1, ID_TEXT_2, ID_TEXT_3, ID_TEXT_4);
        Text_Show(WM_GetDialogItem(pMsg->hWin, ID_TEXT_0), &XBF36_Font, GUI_BLACK, "请选择充电枪");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0), GUI_TA_HCENTER | GUI_TA_VCENTER,
                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "A枪");
        Button_Show(WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1), GUI_TA_HCENTER | GUI_TA_VCENTER,
                    &XBF24_Font, BUTTON_CI_UNPRESSED, GUI_BLUE, BUTTON_CI_UNPRESSED, GUI_BLUE, "B枪");
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch(Id)
        {
        case ID_BUTTON_0:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                WM_DeleteWindow(pMsg->hWin);
                PutOut_Home();
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_DeleteWindow(pMsg->hWin);
                PutOut_Home();
                break;
            }
            break;
        case ID_BUTTON_1:
            switch(NCode)
            {
            case WM_NOTIFICATION_CLICKED:
                WM_DeleteWindow(pMsg->hWin);
                PutOut_Home();
                break;
            case WM_NOTIFICATION_RELEASED:
                WM_DeleteWindow(pMsg->hWin);
                PutOut_Home();
                break;
            }
            break;
        }
        break;
    case WM_TIMER:
        /* 显示时间和日期 */
        Timer_Process(pMsg);
        /* 重启定时器 */
        WM_RestartTimer(pMsg->Data.v, 20);
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}
/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSelAOrB
*/
WM_HWIN CreateSelAOrB(void);
WM_HWIN CreateSelAOrB(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    WM_CreateTimer(WM_GetClientWindow(hWin), ID_TimerTime, 1000, 0);

//    WM_CreateTimer(hWin, ID_TimerTime, 1000, 0);

    return hWin;
}

// USER START (Optionally insert additional public code)
/** @brief
 *  输出充电桩选择AB枪的界面(此页为无人操作中的最初界面即首页)
 * @param
 * @param
 * @return
 *
 */
void PutOut_SelAOrB()
{
    WM_HWIN hWin;
    EventBits_t uxBitRFID;
    hWin = CreateSelAOrB();

    while(1)
    {
        GUI_Delay(500);
        dispbmp("system/dpc.bmp", 0, 5, 5, 1, 1);
        vTaskDelay(500);
    }
}
// USER END

/*************************** End of file ****************************/


